import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES_LIST = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' }
];

const UI_TRANSLATIONS = {
  hi: {
    "Dashboard": "डैशबोर्ड",
    "New Assessment": "नया मूल्यांकन",
    "New assessment": "नया मूल्यांकन",
    "Reports History": "रिपोर्ट इतिहास",
    "Reports": "रिपोर्ट्स",
    "Improvement Plan": "सुधार योजना",
    "Business Alternatives": "व्यवसाय विकल्प",
    "Financial Plan": "वित्तीय योजना",
    "Legal Advice": "कानूनी सलाह",
    "Legal Advice & Documentation": "कानूनी सलाह एवं दस्तावेज़ीकरण",
    "Profile": "प्रोफ़ाइल",
    "Sign Out": "साइन आउट",
    "Decision tools": "निर्णय उपकरण",
    "Prototype data": "प्रोटोटाइप डेटा",
    "Decision Dashboard": "निर्णय डैशबोर्ड",
    "Your business assessment": "आपका व्यवसाय मूल्यांकन",
    "Pre-investment advisory overview and village catchment intelligence.": "निवेश-पूर्व सलाह अवलोकन और ग्रामीण मांग बुद्धिमत्ता।",
    "Full report": "पूर्ण रिपोर्ट",
    "Latest assessment": "नवीनतम मूल्यांकन",
    "Local catchment · 10 km": "स्थानीय क्षेत्र · 10 किमी",
    "Map view": "मानचित्र दृश्य",
    "No completed assessments yet": "अभी तक कोई पूर्ण मूल्यांकन नहीं",
    "Start your first assessment": "अपना पहला मूल्यांकन शुरू करें",
    "Back to results": "परिणामों पर वापस",
    "Download report": "रिपोर्ट डाउनलोड करें",
    "Print plan": "योजना प्रिंट करें",
    "Compare Selected (2)": "चयनित की तुलना करें (2)",
    "Compare Selected": "चयनित की तुलना करें",
    "Begin assessment": "मूल्यांकन शुरू करें",
    "Continue to business": "व्यवसाय पर जारी रखें",
    "Continue to readiness": "तैयारी पर जारी रखें",
    "Continue to finance": "वित्त पर जारी रखें",
    "Continue to review": "समीक्षा पर जारी रखें",
    "Run Feasibility Analysis →": "व्यवहार्यता विश्लेषण चलाएं →",
    "Back": "वापस",
    "Edit": "संपादित करें",
    "Save changes": "बदलाव सहेजें",
    "Log in": "लॉग इन",
    "Create account": "खाता बनाएं",
    "Notifications": "सूचनाएं",
    "No new notifications": "कोई नई सूचना नहीं",
    "Local Market Fit": "स्थानीय बाज़ार फिट",
    "Entrepreneur Readiness": "उद्यमी तत्परता",
    "Financial Fit": "वित्तीय फिट",
    "Verdict Band": "फैसला बैंड",
    "Feasibility": "व्यवहार्यता",
    "Strengths": "ताकत",
    "Weaknesses": "कमजोरियां",
    "Opportunities": "अवसर",
    "Threats": "खतरे",
    "Market Fit": "बाज़ार फिट",
    "Capital Fit": "पूंजी फिट",
    "Resource Fit": "संसाधन फिट",
    "Best fit": "सर्वोत्तम फिट",
    "Fit score": "फिट स्कोर",
    "Recommended Schemes": "अनुशंसित योजनाएं",
    "Estimated EMI": "अनुमानित ईएमआई",
    "Monthly Profit": "मासिक लाभ",
    "Break-even Period": "ब्रेक-इवन अवधि",
    "Priority Actions": "प्राथमिकता वाले कार्य",
    "Legal Advice & Registration Support": "कानूनी सलाह और पंजीकरण सहायता",
    "Assessment history": "मूल्यांकन इतिहास",
    "User Profile": "उपयोगकर्ता प्रोफ़ाइल",
    "Personal details": "व्यक्तिगत विवरण",
    "Accessibility Settings": "सुलभता सेटिंग्स"
  },
  mr: {
    "Dashboard": "डॅशबोर्ड",
    "New Assessment": "नवीन मूल्यमापन",
    "New assessment": "नवीन मूल्यमापन",
    "Reports History": "अहवाल इतिहास",
    "Reports": "अहवाल",
    "Improvement Plan": "सुधारणा योजना",
    "Business Alternatives": "व्यवसाय पर्याय",
    "Financial Plan": "आर्थिक योजना",
    "Legal Advice": "कायदेशीर सल्ला",
    "Legal Advice & Documentation": "कायदेशीर सल्ला आणि कागदपत्रे",
    "Profile": "प्रोफाइल",
    "Sign Out": "साइन आउट",
    "Decision tools": "निर्णय साधने",
    "Prototype data": "प्रोटोटाइप डेटा",
    "Decision Dashboard": "निर्णय डॅशबोर्ड",
    "Your business assessment": "तुमचे व्यवसाय मूल्यमापन",
    "Pre-investment advisory overview and village catchment intelligence.": "गुंतवणूक-पूर्व सल्लागार विहंगावलोकन आणि ग्रामीण मागणी बुद्धिमत्ता.",
    "Full report": "पूर्ण अहवाल",
    "Latest assessment": "नवीनतम मूल्यमापन",
    "Local catchment · 10 km": "स्थानिक परिसर · १० किमी",
    "Map view": "नकाशा दृश्य",
    "No completed assessments yet": "अद्याप कोणतेही पूर्ण मूल्यमापन नाही",
    "Start your first assessment": "तुमचे पहिले मूल्यमापन सुरू करा",
    "Back to results": "निकाल कडे परत",
    "Download report": "अहवाल डाउनलोड करा",
    "Print plan": "योजना प्रिंट करा",
    "Compare Selected (2)": "निवडलेल्यांची तुलना करा (2)",
    "Compare Selected": "निवडलेल्यांची तुलना करा",
    "Begin assessment": "मूल्यमापन सुरू करा",
    "Continue to business": "व्यवसायाकडे पुढे जा",
    "Continue to readiness": "तयारीकडे पुढे जा",
    "Continue to finance": "आर्थिक बाबींकडे पुढे जा",
    "Continue to review": "पुनरावलोकनाकडे पुढे जा",
    "Run Feasibility Analysis →": "व्यावहारिकता विश्लेषण चालवा →",
    "Back": "मागे",
    "Edit": "संपादित करा",
    "Save changes": "बदल जतन करा",
    "Log in": "लॉग इन",
    "Create account": "खाते तयार करा",
    "Notifications": "सूचना",
    "No new notifications": "नवीन सूचना नाहीत",
    "Local Market Fit": "स्थानिक बाजार फिट",
    "Entrepreneur Readiness": "उद्योजक तयारी",
    "Financial Fit": "आर्थिक फिट",
    "Verdict Band": "निर्णय बँड",
    "Feasibility": "व्यावहारिकता",
    "Strengths": "सामर्थ्ये",
    "Weaknesses": "उणिवा",
    "Opportunities": "संधी",
    "Threats": "धोके",
    "Market Fit": "बाजार फिट",
    "Capital Fit": "भांडवल फिट",
    "Resource Fit": "संसाधन फिट",
    "Best fit": "सर्वोत्तम फिट",
    "Fit score": "फिट स्कोर",
    "Recommended Schemes": "शिफारस केलेल्या योजना",
    "Estimated EMI": "अंदाजित ईएमआय",
    "Monthly Profit": "मासिक नफा",
    "Break-even Period": "ब्रेक-इव्हन कालावधी",
    "Priority Actions": "प्राधान्य कृती",
    "Legal Advice & Registration Support": "कायदेशीर सल्ला आणि नोंदणी मदत",
    "Assessment history": "मूल्यमापन इतिहास",
    "User Profile": "वापरकर्ता प्रोफाइल",
    "Personal details": "वैयक्तिक तपशील",
    "Accessibility Settings": "सुलभता सेटिंग्ज"
  },
  ta: {
    "Dashboard": "டாஷ்போர்டு",
    "New Assessment": "புதிய மதிப்பீடு",
    "New assessment": "புதிய மதிப்பீடு",
    "Reports History": "அறிக்கைகள் வரலாறு",
    "Reports": "அறிக்கைகள்",
    "Improvement Plan": "மேம்பாட்டுத் திட்டம்",
    "Business Alternatives": "வணிக மாற்றுக்கள்",
    "Financial Plan": "நிதித் திட்டம்",
    "Legal Advice": "சட்ட ஆலோசனை",
    "Legal Advice & Documentation": "சட்ட ஆலோசனை & ஆவணங்கள்",
    "Profile": "சுயவிவரம்",
    "Sign Out": "வெளியேறு",
    "Decision tools": "முடிவு கருவிகள்",
    "Prototype data": "முன்னோடி தரவு",
    "Decision Dashboard": "முடிவு டாஷ்போர்டு",
    "Your business assessment": "உங்கள் வணிக மதிப்பீடு",
    "Full report": "முழு அறிக்கை",
    "Latest assessment": "சமீபத்திய மதிப்பீடு",
    "Back to results": "முடிவுகளுக்குத் திரும்பு",
    "Download report": "அறிக்கையைப் பதிவிறக்குக",
    "Print plan": "திட்டத்தை அச்சிடுக",
    "Compare Selected": "தேர்ந்தெடுக்கப்பட்டதை ஒப்பிடுக",
    "Begin assessment": "மதிப்பீட்டைத் தொடங்குங்கள்",
    "Continue to business": "வணிகத்திற்கு தொடரவும்",
    "Continue to readiness": "தயார்நிலைக்கு தொடரவும்",
    "Continue to finance": "நிதிக்கு தொடரவும்",
    "Continue to review": "மதிப்பாய்வுக்கு தொடரவும்",
    "Run Feasibility Analysis →": "சாத்தியக்கூறு பகுப்பாய்வு செய்க →",
    "Back": "பின்னால்",
    "Edit": "திருத்து",
    "Save changes": "மாற்றங்களைச் சேமிக்கவும்",
    "Log in": "உள்நுழைய",
    "Create account": "கணக்கை உருவாக்கு",
    "Notifications": "அறிவிப்புகள்",
    "No new notifications": "புதிய அறிவிப்புகள் இல்லை",
    "Local Market Fit": "உள்ளூர் சந்தை பொருத்தம்",
    "Entrepreneur Readiness": "தொழில்முனைவோர் தயார்நிலை",
    "Financial Fit": "நிதி பொருத்தம்",
    "Strengths": "பலம்",
    "Weaknesses": "பலவீனம்",
    "Opportunities": "வாய்ப்புகள்",
    "Threats": "அச்சுறுத்தல்கள்",
    "Priority Actions": "முன்னுரிமை நடவடிக்கைகள்"
  },
  te: {
    "Dashboard": "డాష్‌బోర్డ్",
    "New Assessment": "కొత్త మూల్యాంకనం",
    "New assessment": "కొత్త మూల్యాంకనం",
    "Reports History": "నివేదికల చరిత్ర",
    "Reports": "నివేదికలు",
    "Improvement Plan": "మెరుగుదల ప్రణాళిక",
    "Business Alternatives": "వ్యాపార ప్రత్యామ్నాయాలు",
    "Financial Plan": "ఆర్థిక ప్రణాళిక",
    "Legal Advice": "చట్టపరమైన సలహా",
    "Legal Advice & Documentation": "చట్టపరమైన సలహా & పత్రాలు",
    "Profile": "ప్రొఫైల్",
    "Sign Out": "సైన్ అవుట్",
    "Decision tools": "నిర్ణయ సాధనాలు",
    "Prototype data": "ప్రోటోటైప్ డేటా",
    "Decision Dashboard": "నిర్ణయ డాష్‌బోర్డ్",
    "Your business assessment": "మీ వ్యాపార మూల్యాంకనం",
    "Full report": "పూర్తి నివేదిక",
    "Latest assessment": "ఇటీవలి మూల్యాంకనం",
    "Back to results": "ఫలితాలకు తిరిగి వెళ్లండి",
    "Download report": "నివేదికను డౌన్‌లోడ్ చేయండి",
    "Print plan": "ప్రణాళికను ప్రింట్ చేయండి",
    "Compare Selected": "ఎంచుకున్న వాటిని పోల్చండి",
    "Begin assessment": "మూల్యాంకనం ప్రారంభించండి",
    "Back": "వెనుకకు",
    "Edit": "సవరించు",
    "Save changes": "మార్పులను సేవ్ చేయండి",
    "Log in": "లాగిన్",
    "Create account": "ఖాతా సృష్టించండి",
    "Notifications": "నోటిఫికేషన్‌లు",
    "No new notifications": "కొత్త నోటిఫికేషన్‌లు లేవు",
    "Priority Actions": "ప్రాధాన్యతా చర్యలు"
  },
  kn: {
    "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "New Assessment": "ಹೊಸ ಮೌಲ್ಯಮಾಪನ",
    "New assessment": "ಹೊಸ ಮೌಲ್ಯಮಾಪನ",
    "Reports History": "ವರದಿಗಳ ಇತಿಹಾಸ",
    "Reports": "ವರದಿಗಳು",
    "Improvement Plan": "ಸುಧಾರಣಾ ಯೋಜನೆ",
    "Business Alternatives": "ವ್ಯಾಪಾರ ಪರ್ಯಾಯಗಳು",
    "Financial Plan": "ಹಣಕಾಸು ಯೋಜನೆ",
    "Legal Advice": "ಕಾನ್ಫರೆನ್ಸ್ ಸಲಹೆ",
    "Legal Advice & Documentation": "ಕಾನ್ಫರೆನ್ಸ್ ಸಲಹೆ ಮತ್ತು ದಾಖಲೆಗಳು",
    "Profile": "ಪ್ರೊಫೈಲ್",
    "Sign Out": "ಸೈನ್ ಔಟ್",
    "Decision tools": "ನಿರ್ಧಾರ ಉಪಕರಣಗಳು",
    "Full report": "ಸಂಪೂರ್ಣ ವರದಿ",
    "Latest assessment": "ಇತ್ತೀಚಿನ ಮೌಲ್ಯಮಾಪನ",
    "Back to results": "ಫಲಿತಾಂಶಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    "Download report": "ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    "Print plan": "ಯೋಜನೆಯನ್ನು ಮುದ್ರಿಸಿ",
    "Compare Selected": "ಆಯ್ಕೆಮಾಡಿದ್ದನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ",
    "Begin assessment": "ಮೌಲ್ಯಮಾಪನ ಪ್ರಾರಂಭಿಸಿ",
    "Back": "ಹಿಂತಿರುಗಿ",
    "Edit": "ಸಂಪಾದಿಸಿ",
    "Save changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    "Log in": "ಲಾಗಿನ್",
    "Create account": "ಖಾತೆ ರಚಿಸಿ",
    "Notifications": "ಸೂಚನೆಗಳು",
    "No new notifications": "ಯಾವುದೇ ಹೊಸ ಸೂಚನೆಗಳಿಲ್ಲ",
    "Priority Actions": "ಆದ್ಯತೆಯ ಕ್ರಮಗಳು"
  },
  bn: {
    "Dashboard": "ড্যাশবোর্ড",
    "New Assessment": "নতুন মূল্যায়ন",
    "New assessment": "নতুন মূল্যায়ন",
    "Reports History": "রিপোর্টের ইতিহাস",
    "Reports": "রিপোর্ট",
    "Improvement Plan": "উন্নয়ন পরিকল্পনা",
    "Business Alternatives": "ব্যবসার বিকল্প",
    "Financial Plan": "আর্থিক পরিকল্পনা",
    "Legal Advice": "আইনি পরামর্শ",
    "Legal Advice & Documentation": "আইনি পরামর্শ ও নথিপত্র",
    "Profile": "প্রোফাইল",
    "Sign Out": "সাইন আউট",
    "Decision tools": "সিদ্ধান্তের সরঞ্জাম",
    "Full report": "সম্পূর্ণ রিপোর্ট",
    "Latest assessment": "সাম্প্রতিক মূল্যায়ন",
    "Back to results": "ফলাফলে ফিরে যান",
    "Download report": "রিপোর্ট ডাউনলোড করুন",
    "Print plan": "পরিকল্পনা প্রিন্ট করুন",
    "Compare Selected": "নির্বাচিতগুলি তুলনা করুন",
    "Begin assessment": "মূল্যায়ন শুরু করুন",
    "Back": "ফিরে যান",
    "Edit": "সম্পাদনা করুন",
    "Save changes": "পরিবর্তনগুলি সংরক্ষণ করুন",
    "Log in": "লগ ইন",
    "Create account": "অ্যাকাউন্ট তৈরি করুন",
    "Notifications": "বিজ্ঞপ্তি",
    "No new notifications": "কোনো নতুন বিজ্ঞপ্তি নেই",
    "Priority Actions": "অগ্রাধিকার পদক্ষেপ"
  },
  gu: {
    "Dashboard": "ડેશબોર્ડ",
    "New Assessment": "નવું મૂલ્યાંકન",
    "New assessment": "નવું મૂલ્યાંકન",
    "Reports History": "રિપોર્ટ ઇતિહાસ",
    "Reports": "રિપોર્ટ્સ",
    "Improvement Plan": "સુધારણા યોજના",
    "Business Alternatives": "વ્યવસાય વિકલ્પો",
    "Financial Plan": "નાણાકીય યોજના",
    "Legal Advice": "કાનૂની સલાહ",
    "Legal Advice & Documentation": "કાનૂની સલાહ અને દસ્તાવેજીકરણ",
    "Profile": "પ્રોફાઇલ",
    "Sign Out": "સાઇન આઉટ",
    "Decision tools": "નિર્ણય સાધનો",
    "Full report": "સંપૂર્ણ રિપોર્ટ",
    "Latest assessment": "તાજેતરનું મૂલ્યાંકન",
    "Back to results": "પરિણામો પર પાછા ફરો",
    "Download report": "રિપોર્ટ ડાઉનલોડ કરો",
    "Print plan": "યોજના પ્રિન્ટ કરો",
    "Compare Selected": "પસંદ કરેલાની સરખામણી કરો",
    "Begin assessment": "મૂલ્યાંકન શરૂ કરો",
    "Back": "પાછા",
    "Edit": "સંપાદિત કરો",
    "Save changes": "ફેરફારો સાચવો",
    "Log in": "લૉગ ઇન",
    "Create account": "ખાતું બનાવો",
    "Notifications": "સૂચનાઓ",
    "No new notifications": "કોઈ નવી સૂચના નથી",
    "Priority Actions": "પ્રાથમિકતા ક્રિયાઓ"
  },
  pa: {
    "Dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "New Assessment": "ਨਵਾਂ ਮੁਲਾਂਕਣ",
    "New assessment": "ਨਵਾਂ ਮੁਲਾਂਕਣ",
    "Reports History": "ਰਿਪੋਰਟ ਇਤਿਹਾਸ",
    "Reports": "ਰਿਪੋਰਟਾਂ",
    "Improvement Plan": "ਸੁਧਾਰ ਯੋਜਨਾ",
    "Business Alternatives": "ਕਾਰੋਬਾਰੀ ਵਿਕਲਪ",
    "Financial Plan": "ਮਾਲੀ ਯੋਜਨਾ",
    "Legal Advice": "ਕਾਨੂੰਨੀ ਸਲਾਹ",
    "Legal Advice & Documentation": "ਕਾਨੂੰਨੀ ਸਲਾਹ ਅਤੇ ਦਸਤਾਵੇਜ਼",
    "Profile": "ਪ੍ਰੋਫਾਈਲ",
    "Sign Out": "ਸਾਈਨ ਆਊਟ",
    "Decision tools": "ਫੈਸਲੇ ਦੇ ਸੰਦ",
    "Full report": "ਪੂਰੀ ਰਿਪੋਰਟ",
    "Latest assessment": "ਤਾਜ਼ਾ ਮੁਲਾਂਕਣ",
    "Back to results": "ਨਤੀਜਿਆਂ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    "Download report": "ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    "Print plan": "ਯੋਜਨਾ ਪ੍ਰਿੰਟ ਕਰੋ",
    "Compare Selected": "ਚੁਣੇ ਗਏ ਦੀ ਤੁਲਨਾ ਕਰੋ",
    "Begin assessment": "ਮੁਲਾਂਕਣ ਸ਼ੁਰੂ ਕਰੋ",
    "Back": "ਵਾਪਸ",
    "Edit": "ਸੋਧੋ",
    "Save changes": "ਬਦਲਾਅ ਸੰਭਾਲੋ",
    "Log in": "ਲੌਗ ਇਨ",
    "Create account": "ਖਾਤਾ ਬਣਾਓ",
    "Notifications": "ਨੋਟੀਫਿਕੇਸ਼ਨ",
    "No new notifications": "ਕੋਈ ਨਵਾਂ ਨੋਟੀਫਿਕੇਸ਼ਨ ਨਹੀਂ",
    "Priority Actions": "ਪਹਿਲ ਦੇ ਕਦਮ"
  }
};

// Prototype-wide copy used by the three supported UI languages. This also
// covers deterministic API strings so a missing server-side model never leaks
// placeholders such as "[Hindi] ..." into the interface.
const PROTOTYPE_TRANSLATIONS = {
  hi: {
    "Feasibility Report": "व्यवहार्यता रिपोर्ट",
    "New Feasibility Assessment": "नया व्यवहार्यता मूल्यांकन",
    "Assessment progress": "मूल्यांकन प्रगति",
    "Pre-investment advisory": "निवेश-पूर्व सलाह",
    "Takes 5–7 minutes": "5–7 मिनट लगते हैं",
    "Answers stored securely": "उत्तर सुरक्षित रूप से संग्रहीत हैं",
    "1. Market Feasibility": "1. बाज़ार व्यवहार्यता",
    "Evaluates 10km village demand, competitor density & infrastructure.": "10 किमी क्षेत्र की ग्रामीण मांग, प्रतिस्पर्धी घनत्व और बुनियादी ढांचे का मूल्यांकन करता है।",
    "2. Entrepreneur Readiness": "2. उद्यमी तत्परता",
    "Assesses your skills, workspace, supplier contacts & customers.": "आपके कौशल, कार्यस्थल, आपूर्तिकर्ता संपर्क और ग्राहकों का आकलन करता है।",
    "3. Financial Fit": "3. वित्तीय उपयुक्तता",
    "Verifies margin sufficiency & monthly disposable EMI capacity.": "मार्जिन पर्याप्तता और मासिक ईएमआई क्षमता की जांच करता है।",
    "Personal Profile & Resources": "व्यक्तिगत प्रोफ़ाइल और संसाधन",
    "Tell us about your background and available operational assets.": "अपनी पृष्ठभूमि और उपलब्ध परिचालन संसाधनों के बारे में बताएं।",
    "Age group": "आयु वर्ग",
    "18–24 years": "18–24 वर्ष",
    "25–34 years": "25–34 वर्ष",
    "35–44 years": "35–44 वर्ष",
    "45+ years": "45+ वर्ष",
    "Education level": "शिक्षा स्तर",
    "Primary school": "प्राथमिक विद्यालय",
    "Secondary (Class 10/12)": "माध्यमिक (कक्षा 10/12)",
    "Graduate / higher": "स्नातक / उच्चतर",
    "No formal education": "कोई औपचारिक शिक्षा नहीं",
    "Current occupation": "वर्तमान व्यवसाय",
    "e.g. Agriculture / Self-employed": "जैसे कृषि / स्वरोज़गार",
    "Prior business experience": "पूर्व व्यावसायिक अनुभव",
    "None (First-time)": "कोई नहीं (पहली बार)",
    "0–2 years": "0–2 वर्ष",
    "3–5 years": "3–5 वर्ष",
    "5+ years": "5+ वर्ष",
    "Education guarantee:": "शिक्षा संबंधी आश्वासन:",
    "Education level does not reduce your feasibility score. It is used strictly to personalize explanation complexity, skill training guidance, and financial-literacy support.": "शिक्षा का स्तर आपके व्यवहार्यता स्कोर को कम नहीं करता। इसका उपयोग केवल समझाने की भाषा, कौशल प्रशिक्षण मार्गदर्शन और वित्तीय साक्षरता सहायता को व्यक्तिगत बनाने के लिए होता है।",
    "Time commitment": "समय की प्रतिबद्धता",
    "Full-time commitment": "पूर्णकालिक प्रतिबद्धता",
    "Part-time": "अंशकालिक",
    "Seasonal": "मौसमी",
    "Family-managed": "परिवार द्वारा संचालित",
    "Existing monthly loan EMI (₹)": "मौजूदा मासिक ऋण ईएमआई (₹)",
    "Select Business Category & Location": "व्यवसाय श्रेणी और स्थान चुनें",
    "Pick your target business and village location for catchment analysis.": "क्षेत्रीय विश्लेषण के लिए लक्षित व्यवसाय और गांव का स्थान चुनें।",
    "Use current location (Mock)": "वर्तमान स्थान उपयोग करें (डेमो)",
    "State": "राज्य",
    "District": "जिला",
    "Block / Sub-District": "ब्लॉक / उप-जिला",
    "Village": "गांव",
    "Answer based on what is available today—not what you hope to arrange later.": "उत्तर आज उपलब्ध संसाधनों के आधार पर दें—भविष्य की आशा के आधार पर नहीं।",
    "Readiness Advisory:": "तत्परता सलाह:",
    "Honest answers make the preparation guidance more useful. Entrepreneur readiness is scored separately from village market feasibility.": "ईमानदार उत्तर तैयारी मार्गदर्शन को अधिक उपयोगी बनाते हैं। उद्यमी तत्परता का स्कोर ग्रामीण बाज़ार व्यवहार्यता से अलग है।",
    "Understand Your Financial Fit": "अपनी वित्तीय उपयुक्तता समझें",
    "Provide your available capital and monthly household obligations.": "अपनी उपलब्ध पूंजी और मासिक घरेलू दायित्व बताएं।",
    "Project cost estimate (₹)": "परियोजना लागत अनुमान (₹)",
    "Available entrepreneur margin capital (₹)": "उपलब्ध उद्यमी मार्जिन पूंजी (₹)",
    "Monthly household expenses (₹)": "मासिक घरेलू खर्च (₹)",
    "Financial understanding": "वित्तीय समझ",
    "Do you understand how EMI works?": "क्या आप समझते हैं कि ईएमआई कैसे काम करती है?",
    "Preliminary demo estimate": "प्रारंभिक डेमो अनुमान",
    "Project cost:": "परियोजना लागत:",
    "Your available margin:": "आपका उपलब्ध मार्जिन:",
    "Min margin needed (10%):": "न्यूनतम आवश्यक मार्जिन (10%):",
    "Indicative loan amount": "संकेतात्मक ऋण राशि",
    "Review Your Inputs": "अपने विवरण की समीक्षा करें",
    "Check your assessment inputs before running the feasibility engine.": "व्यवहार्यता विश्लेषण चलाने से पहले अपने विवरण जांच लें।",
    "1. Personal profile": "1. व्यक्तिगत प्रोफ़ाइल",
    "2. Business & location": "2. व्यवसाय और स्थान",
    "Category questionnaire completed": "श्रेणी प्रश्नावली पूर्ण",
    "4. Financial setup": "4. वित्तीय व्यवस्था",
    "Prototype analysis": "प्रोटोटाइप विश्लेषण",
    "Building your feasibility picture": "आपकी व्यवहार्यता रिपोर्ट तैयार हो रही है",
    "Loading dashboard intelligence...": "डैशबोर्ड जानकारी लोड हो रही है...",
    "Nearby villages in 10km:": "10 किमी में नज़दीकी गांव:",
    "Total population:": "कुल जनसंख्या:",
    "Village ID": "गांव आईडी",
    "Village ID:": "गांव आईडी:",
    "Market around": "आसपास का बाज़ार",
    "Prototype guidance": "प्रोटोटाइप मार्गदर्शन",
    "Recommendations use prototype data and deterministic scoring models. Guidance does not guarantee business financial success or loan approval.": "सिफारिशें प्रोटोटाइप डेटा और निर्धारित गणना मॉडल पर आधारित हैं। यह मार्गदर्शन व्यवसाय की सफलता या ऋण स्वीकृति की गारंटी नहीं देता।",
    "All your saved and completed business feasibility assessments.": "आपके सभी सहेजे गए और पूर्ण व्यवसाय व्यवहार्यता मूल्यांकन।",
    "Compare selected (2)": "चयनित की तुलना करें (2)",
    "Loading assessment history...": "मूल्यांकन इतिहास लोड हो रहा है...",
    "No reports generated yet": "अभी तक कोई रिपोर्ट तैयार नहीं हुई",
    "Run a feasibility assessment to save and compare reports.": "रिपोर्ट सहेजने और तुलना करने के लिए व्यवहार्यता मूल्यांकन चलाएं।",
    "Select any 2 assessments to compare side-by-side.": "साथ-साथ तुलना के लिए कोई भी 2 मूल्यांकन चुनें।",
    "Select": "चुनें",
    "Business category": "व्यवसाय श्रेणी",
    "Feasibility score": "व्यवहार्यता स्कोर",
    "Status": "स्थिति",
    "Date": "तारीख",
    "Actions": "कार्रवाइयां",
    "Draft": "मसौदा",
    "complete": "पूर्ण",
    "Completed": "पूर्ण",
    "Pending": "शुरू नहीं हुआ",
    "Not Started": "शुरू नहीं हुआ",
    "In Progress": "प्रगति पर",
    "View Report": "रिपोर्ट देखें",
    "Download Report": "रिपोर्ट डाउनलोड करें",
    "Preparation before launch": "शुरुआत से पहले तैयारी",
    "Concrete action items to strengthen your entrepreneur readiness before starting.": "शुरू करने से पहले उद्यमी तत्परता मजबूत करने के ठोस कार्य।",
    "Loading readiness action items...": "तत्परता संबंधी कार्य लोड हो रहे हैं...",
    "Current": "वर्तमान",
    "Potential": "संभावित",
    "Potential Preparedness": "संभावित तत्परता",
    "points gained from completed actions": "पूर्ण कार्यों से प्राप्त अंक",
    "of": "में से",
    "Actions Completed": "कार्य पूर्ण",
    "Recommended Action Items": "अनुशंसित कार्य",
    "Readiness": "तत्परता",
    "Dimension:": "आयाम:",
    "Experience": "अनुभव",
    "Skill": "कौशल",
    "Resources": "संसाधन",
    "Complete 2-Week Domain Apprenticeship": "2 सप्ताह की क्षेत्रीय प्रशिक्षुता पूरी करें",
    "Shadow an established shop owner in a nearby town to learn practical daily operations.": "दैनिक कामकाज सीखने के लिए पास के शहर में किसी अनुभवी दुकानदार के साथ प्रशिक्षण लें।",
    "Enroll in RSETI / Skill India Dairy Training": "आरसेटी / स्किल इंडिया डेयरी प्रशिक्षण में नामांकन करें",
    "Undergo certified technical skill and equipment maintenance training for Dairy.": "डेयरी के लिए प्रमाणित तकनीकी कौशल और उपकरण रखरखाव प्रशिक्षण लें।",
    "Finalize Workspace Lease Agreement": "कार्यस्थल का पट्टा समझौता अंतिम करें",
    "Secure a roadside workspace location with adequate power fitting and public access.": "पर्याप्त बिजली और सार्वजनिक पहुंच वाला सड़क किनारे कार्यस्थल सुनिश्चित करें।",
    "This reflects improved preparedness, not guaranteed business financial success. The potential score assumes every listed action is completed.": "यह बेहतर तैयारी दर्शाता है, व्यवसाय की वित्तीय सफलता की गारंटी नहीं। संभावित स्कोर सभी सूचीबद्ध कार्य पूरे होने की धारणा पर आधारित है।",
    "Business ↔ Person ↔ Location": "व्यवसाय ↔ व्यक्ति ↔ स्थान",
    "Demo estimates": "डेमो अनुमान",
    "Ranked comparison of 5 business categories for your village location and capital.": "आपके गांव और पूंजी के आधार पर 5 व्यवसाय श्रेणियों की क्रमबद्ध तुलना।",
    "Evaluating 5 business alternatives...": "5 व्यवसाय विकल्पों का मूल्यांकन हो रहा है...",
    "Explore This Business →": "इस व्यवसाय को देखें →",
    "Strong Fit": "मजबूत उपयुक्तता",
    "Promising": "आशाजनक",
    "Moderate": "मध्यम",
    "Weak": "कमजोर",
    "Poor": "कमज़ोर",
    "Good": "अच्छी",
    "Dairy": "डेयरी",
    "Dairy Farming & Milk Collection": "डेयरी पालन और दूध संग्रह",
    "Small-scale Poultry Unit": "लघु पोल्ट्री इकाई",
    "Tailoring & Garment Shop": "सिलाई और परिधान दुकान",
    "Flour Mill (Atta Chakki)": "आटा चक्की",
    "Two-Wheeler Workshop": "दोपहिया वाहन कार्यशाला",
    "Good market demand with moderate setup capital requirement.": "अच्छी बाज़ार मांग और मध्यम स्थापना पूंजी की आवश्यकता।",
    "Feasible business option but requires capital scale adjustment.": "व्यवहार्य व्यवसाय विकल्प, लेकिन पूंजी स्तर में बदलाव आवश्यक है।",
    "Higher capital barrier or lower demand gap in catchment.": "अधिक पूंजी बाधा या स्थानीय क्षेत्र में कम मांग-अंतर।",
    "Alternative scores are prototype comparisons for decision support. They do not guarantee business performance.": "वैकल्पिक स्कोर निर्णय सहायता के लिए प्रोटोटाइप तुलना हैं। ये व्यवसाय प्रदर्शन की गारंटी नहीं देते।",
    "Financial fit · Demo estimate": "वित्तीय उपयुक्तता · डेमो अनुमान",
    "Scheme matching": "योजना मिलान",
    "Government loan scheme details, reducing-balance EMI calculation, and 90-day roadmap.": "सरकारी ऋण योजना का विवरण, घटती शेष राशि पर ईएमआई गणना और 90-दिवसीय कार्ययोजना।",
    "Loading financial plan calculations...": "वित्तीय योजना की गणना लोड हो रही है...",
    "Your margin": "आपका मार्जिन",
    "Project cost": "परियोजना लागत",
    "Indicative loan": "संकेतात्मक ऋण",
    "Indicative scheme": "संकेतात्मक योजना",
    "Government tier": "सरकारी श्रेणी",
    "Government Rural Term Loan Scheme": "सरकारी ग्रामीण सावधि ऋण योजना",
    "Term loan for project setup between ₹1.40 Lakh and ₹50.00 Lakh with 8% interest rate and 6-month moratorium.": "₹1.40 लाख से ₹50.00 लाख तक परियोजना स्थापना ऋण, 8% ब्याज दर और 6 महीने की स्थगन अवधि के साथ।",
    "Interest rate": "ब्याज दर",
    "Tenure": "अवधि",
    "Moratorium period": "स्थगन अवधि",
    "Monthly EMI": "मासिक ईएमआई",
    "Years": "वर्ष",
    "Mos": "माह",
    "Months": "महीने",
    "Scheme terms are illustrative and must be verified at your local bank branch before applying.": "योजना की शर्तें उदाहरणात्मक हैं; आवेदन से पहले स्थानीय बैंक शाखा में पुष्टि करें।",
    "Monthly affordability": "मासिक वहनीयता",
    "Safe (<40%)": "सुरक्षित (<40%)",
    "Moderate (40-60%)": "मध्यम (40-60%)",
    "High Risk (>60%)": "उच्च जोखिम (>60%)",
    "Estimated EMI:": "अनुमानित ईएमआई:",
    "Household Expenses:": "घरेलू खर्च:",
    "This indicator highlights potential debt pressure; it is not loan approval.": "यह संकेतक संभावित ऋण दबाव दिखाता है; यह ऋण स्वीकृति नहीं है।",
    "Know before you borrow": "ऋण लेने से पहले जानें",
    "Financial Literacy Notes": "वित्तीय साक्षरता नोट्स",
    "What is EMI?": "ईएमआई क्या है?",
    "Equated Monthly Installment is a fixed monthly payment covering principal and reducing-balance interest.": "समान मासिक किस्त एक निश्चित मासिक भुगतान है, जिसमें मूलधन और घटती शेष राशि का ब्याज शामिल होता है।",
    "What is a Moratorium?": "स्थगन अवधि क्या है?",
    "A grace period (3 to 6 months) allowing you to set up operations before monthly principal EMI begins.": "3 से 6 महीने की छूट अवधि, जिसमें मासिक मूलधन ईएमआई शुरू होने से पहले व्यवसाय स्थापित किया जा सकता है।",
    "Repayment Risk": "पुनर्भुगतान जोखिम",
    "Keeping total monthly debt payments under 40% of disposable capacity prevents default in low-income months.": "कुल मासिक ऋण भुगतान को उपलब्ध क्षमता के 40% से कम रखने से कम आय वाले महीनों में चूक का जोखिम घटता है।",
    "Emergency Reserve": "आपातकालीन आरक्षित निधि",
    "Maintain ₹15,000+ liquid reserve to cushion inventory spikes or equipment repairs without missing EMIs.": "ईएमआई चूके बिना स्टॉक वृद्धि या उपकरण मरम्मत के लिए ₹15,000 से अधिक नकद आरक्षित रखें।",
    "Moratorium interest note:": "स्थगन ब्याज नोट:",
    "From preparation to launch": "तैयारी से शुरुआत तक",
    "90-Day Execution Roadmap": "90-दिवसीय कार्ययोजना",
    "Days 1–30": "दिन 1–30",
    "Days 31–60": "दिन 31–60",
    "Days 61–90": "दिन 61–90",
    "Submit loan application at bank branch.": "बैंक शाखा में ऋण आवेदन जमा करें।",
    "Apply for Udyam MSME & Panchayat NOC.": "उद्यम एमएसएमई और पंचायत एनओसी के लिए आवेदन करें।",
    "Secure workspace lease agreement.": "कार्यस्थल का पट्टा समझौता सुनिश्चित करें।",
    "Deposit entrepreneur margin contribution.": "उद्यमी मार्जिन अंशदान जमा करें।",
    "Procure machinery & raw material inventory.": "मशीनरी और कच्चा माल खरीदें।",
    "Install equipment and test trials.": "उपकरण स्थापित कर परीक्षण करें।",
    "Distribute local launch pamphlets.": "स्थानीय प्रचार पर्चे वितरित करें।",
    "Official commercial business launch.": "व्यवसाय का आधिकारिक वाणिज्यिक शुभारंभ करें।",
    "Prepare for post-moratorium EMI repayment.": "स्थगन अवधि के बाद ईएमआई भुगतान की तैयारी करें।",
    "Financial calculations are demo estimates. Final loan approval and interest rates depend on bank credit appraisal.": "वित्तीय गणनाएं डेमो अनुमान हैं। अंतिम ऋण स्वीकृति और ब्याज दर बैंक के ऋण मूल्यांकन पर निर्भर हैं।",
    "Regulatory & aid directory": "नियामक और सहायता निर्देशिका",
    "Find nearby District Legal Services Authorities and required business registration documents.": "नज़दीकी जिला विधिक सेवा प्राधिकरण और आवश्यक व्यवसाय पंजीकरण दस्तावेज़ खोजें।",
    "Loading nearest legal offices and document checklists...": "नज़दीकी कानूनी कार्यालय और दस्तावेज़ सूची लोड हो रही है...",
    "District aid centres": "जिला सहायता केंद्र",
    "Legal & registration support near you": "आपके पास कानूनी और पंजीकरण सहायता",
    "Contact official legal services authorities for MSME registration and report review.": "एमएसएमई पंजीकरण और रिपोर्ट समीक्षा के लिए आधिकारिक विधिक सेवा प्राधिकरणों से संपर्क करें।",
    "District Legal Services Authority": "जिला विधिक सेवा प्राधिकरण",
    "District Industries Centre": "जिला उद्योग केंद्र",
    "Regulatory compliance": "नियामक अनुपालन",
    "Required identity documents and local government trade licenses.": "आवश्यक पहचान दस्तावेज़ और स्थानीय सरकारी व्यापार लाइसेंस।",
    "Required Identity & Bank Documents": "आवश्यक पहचान और बैंक दस्तावेज़",
    "Regulatory & Trade Requirements": "नियामक और व्यापार आवश्यकताएं",
    "report review": "रिपोर्ट समीक्षा",
    "msme registration": "एमएसएमई पंजीकरण",
    "general legal aid": "सामान्य कानूनी सहायता",
    "micro finance counseling": "सूक्ष्म वित्त परामर्श",
    "subsidies guidance": "सब्सिडी मार्गदर्शन",
    "scheme verification": "योजना सत्यापन",
    "Account": "खाता",
    "Manage your personal details, language preferences, and accessibility settings.": "अपने व्यक्तिगत विवरण, भाषा प्राथमिकता और सुलभता सेटिंग्स प्रबंधित करें।",
    "Edit profile": "प्रोफ़ाइल संपादित करें",
    "Cancel editing": "संपादन रद्द करें",
    "Profile Complete": "प्रोफ़ाइल पूर्ण",
    "Profile details": "प्रोफ़ाइल विवरण",
    "Full name": "पूरा नाम",
    "Mobile": "मोबाइल",
    "Mobile number": "मोबाइल नंबर",
    "Email address": "ईमेल पता",
    "Preferred language": "पसंदीदा भाषा",
    "State & district": "राज्य और जिला",
    "Preferences & accessibility": "प्राथमिकताएं और सुलभता",
    "App Preferences": "ऐप प्राथमिकताएं",
    "App language": "ऐप की भाषा",
    "English, Hindi and Marathi supported": "अंग्रेज़ी, हिन्दी और मराठी समर्थित हैं",
    "Accessibility preferences": "सुलभता प्राथमिकताएं",
    "High-contrast visuals and reduced animation settings": "उच्च-कंट्रास्ट दृश्य और कम एनीमेशन सेटिंग्स",
    "High contrast": "उच्च कंट्रास्ट",
    "Reduced motion": "कम गति",
    "Sign Out of Account": "खाते से साइन आउट करें",
    "Clears active session token from browser local storage.": "ब्राउज़र के स्थानीय संग्रह से सक्रिय सत्र टोकन हटाता है।",
    "Rural Micro-Entrepreneur": "ग्रामीण सूक्ष्म-उद्यमी",
    "English": "अंग्रेज़ी",
    "Hindi": "हिन्दी",
    "Marathi": "मराठी",
    "Welcome back": "फिर से स्वागत है",
    "Log in to your account": "अपने खाते में लॉग इन करें",
    "Password": "पासवर्ड",
    "Remember me": "मुझे याद रखें",
    "Get started": "शुरू करें",
    "Create your account": "अपना खाता बनाएं",
    "Confirm password": "पासवर्ड की पुष्टि करें",
    "Creating account...": "खाता बनाया जा रहा है...",
    "Already have an account?": "क्या आपके पास पहले से खाता है?",
    "Instant village-level demand analysis": "गांव-स्तरीय मांग का त्वरित विश्लेषण",
    "Readiness preparation action plan": "तत्परता तैयारी कार्ययोजना",
    "Local legal office directory & checklists": "स्थानीय कानूनी कार्यालय निर्देशिका और जांच सूची",
    "Catchment legend": "स्थानीय क्षेत्र संकेत",
    "10 km radius circle": "10 किमी त्रिज्या वृत्त",
    "Competitor shops": "प्रतिस्पर्धी दुकानें",
    "Selected Village Center": "चयनित गांव केंद्र",
    "Distance:": "दूरी:",
    "We analyse nearby villages, local population, business density, and infrastructure within approximately 10 km for the selected business only.": "हम केवल चयनित व्यवसाय के लिए लगभग 10 किमी के भीतर नज़दीकी गांवों, जनसंख्या, व्यवसाय घनत्व और बुनियादी ढांचे का विश्लेषण करते हैं।"
  },
  mr: {
    "Feasibility Report": "व्यवहार्यता अहवाल",
    "New Feasibility Assessment": "नवीन व्यवहार्यता मूल्यमापन",
    "Assessment progress": "मूल्यमापन प्रगती",
    "Pre-investment advisory": "गुंतवणूक-पूर्व मार्गदर्शन",
    "Takes 5–7 minutes": "5–7 मिनिटे लागतात",
    "Answers stored securely": "उत्तरे सुरक्षितपणे जतन केली जातात",
    "1. Market Feasibility": "1. बाजार व्यवहार्यता",
    "Evaluates 10km village demand, competitor density & infrastructure.": "10 किमी परिसरातील गावाची मागणी, स्पर्धकांची घनता आणि पायाभूत सुविधांचे मूल्यमापन करते.",
    "2. Entrepreneur Readiness": "2. उद्योजक तयारी",
    "Assesses your skills, workspace, supplier contacts & customers.": "तुमची कौशल्ये, कार्यस्थळ, पुरवठादार संपर्क आणि ग्राहकांचे मूल्यमापन करते.",
    "3. Financial Fit": "3. आर्थिक योग्यता",
    "Verifies margin sufficiency & monthly disposable EMI capacity.": "मार्जिनची पर्याप्तता आणि मासिक ईएमआय क्षमतेची तपासणी करते.",
    "Personal Profile & Resources": "वैयक्तिक प्रोफाइल आणि संसाधने",
    "Tell us about your background and available operational assets.": "तुमची पार्श्वभूमी आणि उपलब्ध कार्यकारी साधनांबद्दल सांगा.",
    "Age group": "वयोगट",
    "18–24 years": "18–24 वर्षे",
    "25–34 years": "25–34 वर्षे",
    "35–44 years": "35–44 वर्षे",
    "45+ years": "45+ वर्षे",
    "Education level": "शिक्षण स्तर",
    "Primary school": "प्राथमिक शाळा",
    "Secondary (Class 10/12)": "माध्यमिक (इयत्ता 10/12)",
    "Graduate / higher": "पदवीधर / उच्च",
    "No formal education": "औपचारिक शिक्षण नाही",
    "Current occupation": "सध्याचा व्यवसाय",
    "e.g. Agriculture / Self-employed": "उदा. शेती / स्वयंरोजगार",
    "Prior business experience": "पूर्वीचा व्यवसाय अनुभव",
    "None (First-time)": "नाही (प्रथमच)",
    "0–2 years": "0–2 वर्षे",
    "3–5 years": "3–5 वर्षे",
    "5+ years": "5+ वर्षे",
    "Education guarantee:": "शिक्षणाबाबत हमी:",
    "Education level does not reduce your feasibility score. It is used strictly to personalize explanation complexity, skill training guidance, and financial-literacy support.": "शिक्षणाचा स्तर तुमचा व्यवहार्यता गुण कमी करत नाही. त्याचा वापर फक्त स्पष्टीकरण, कौशल्य प्रशिक्षण आणि आर्थिक साक्षरता मार्गदर्शन वैयक्तिक करण्यासाठी होतो.",
    "Time commitment": "वेळेची बांधिलकी",
    "Full-time commitment": "पूर्णवेळ बांधिलकी",
    "Part-time": "अर्धवेळ",
    "Seasonal": "हंगामी",
    "Family-managed": "कुटुंबाद्वारे व्यवस्थापित",
    "Existing monthly loan EMI (₹)": "सध्याची मासिक कर्ज ईएमआय (₹)",
    "Select Business Category & Location": "व्यवसाय श्रेणी आणि ठिकाण निवडा",
    "Pick your target business and village location for catchment analysis.": "परिसर विश्लेषणासाठी अपेक्षित व्यवसाय आणि गावाचे ठिकाण निवडा.",
    "Use current location (Mock)": "सध्याचे ठिकाण वापरा (डेमो)",
    "State": "राज्य",
    "District": "जिल्हा",
    "Block / Sub-District": "तालुका / उप-जिल्हा",
    "Village": "गाव",
    "Answer based on what is available today—not what you hope to arrange later.": "आज उपलब्ध असलेल्या गोष्टींवर आधारित उत्तर द्या—भविष्यातील अपेक्षांवर नाही.",
    "Readiness Advisory:": "तयारीविषयक सल्ला:",
    "Honest answers make the preparation guidance more useful. Entrepreneur readiness is scored separately from village market feasibility.": "प्रामाणिक उत्तरे तयारीचे मार्गदर्शन अधिक उपयुक्त करतात. उद्योजक तयारीचे गुण गावाच्या बाजार व्यवहार्यतेपासून स्वतंत्र आहेत.",
    "Understand Your Financial Fit": "तुमची आर्थिक योग्यता समजून घ्या",
    "Provide your available capital and monthly household obligations.": "तुमचे उपलब्ध भांडवल आणि मासिक घरगुती जबाबदाऱ्या सांगा.",
    "Project cost estimate (₹)": "प्रकल्प खर्चाचा अंदाज (₹)",
    "Available entrepreneur margin capital (₹)": "उपलब्ध उद्योजक मार्जिन भांडवल (₹)",
    "Monthly household expenses (₹)": "मासिक घरगुती खर्च (₹)",
    "Financial understanding": "आर्थिक समज",
    "Do you understand how EMI works?": "ईएमआय कशी कार्य करते हे तुम्हाला समजते का?",
    "Preliminary demo estimate": "प्राथमिक डेमो अंदाज",
    "Project cost:": "प्रकल्प खर्च:",
    "Your available margin:": "तुमचे उपलब्ध मार्जिन:",
    "Min margin needed (10%):": "किमान आवश्यक मार्जिन (10%):",
    "Indicative loan amount": "सूचक कर्ज रक्कम",
    "Review Your Inputs": "तुमच्या माहितीचे पुनरावलोकन करा",
    "Check your assessment inputs before running the feasibility engine.": "व्यवहार्यता विश्लेषण चालवण्यापूर्वी दिलेली माहिती तपासा.",
    "1. Personal profile": "1. वैयक्तिक प्रोफाइल",
    "2. Business & location": "2. व्यवसाय आणि ठिकाण",
    "Category questionnaire completed": "श्रेणी प्रश्नावली पूर्ण",
    "4. Financial setup": "4. आर्थिक व्यवस्था",
    "Prototype analysis": "प्रोटोटाइप विश्लेषण",
    "Building your feasibility picture": "तुमचा व्यवहार्यता अहवाल तयार होत आहे",
    "Loading dashboard intelligence...": "डॅशबोर्ड माहिती लोड होत आहे...",
    "Nearby villages in 10km:": "10 किमीतील जवळची गावे:",
    "Total population:": "एकूण लोकसंख्या:",
    "Village ID": "गाव आयडी",
    "Village ID:": "गाव आयडी:",
    "Market around": "परिसरातील बाजार",
    "Prototype guidance": "प्रोटोटाइप मार्गदर्शन",
    "Recommendations use prototype data and deterministic scoring models. Guidance does not guarantee business financial success or loan approval.": "शिफारसी प्रोटोटाइप डेटा आणि निश्चित गणना मॉडेलवर आधारित आहेत. हे मार्गदर्शन व्यवसाय यश किंवा कर्ज मंजुरीची हमी देत नाही.",
    "All your saved and completed business feasibility assessments.": "तुमची सर्व जतन केलेली आणि पूर्ण व्यवसाय व्यवहार्यता मूल्यमापने.",
    "Compare selected (2)": "निवडलेल्यांची तुलना करा (2)",
    "Loading assessment history...": "मूल्यमापन इतिहास लोड होत आहे...",
    "No reports generated yet": "अद्याप कोणताही अहवाल तयार नाही",
    "Run a feasibility assessment to save and compare reports.": "अहवाल जतन व तुलना करण्यासाठी व्यवहार्यता मूल्यमापन चालवा.",
    "Select any 2 assessments to compare side-by-side.": "शेजारी तुलना करण्यासाठी कोणतीही 2 मूल्यमापने निवडा.",
    "Select": "निवडा",
    "Business category": "व्यवसाय श्रेणी",
    "Feasibility score": "व्यवहार्यता गुण",
    "Status": "स्थिती",
    "Date": "दिनांक",
    "Actions": "कृती",
    "Draft": "मसुदा",
    "complete": "पूर्ण",
    "Completed": "पूर्ण",
    "Pending": "सुरू केलेले नाही",
    "Not Started": "सुरू केलेले नाही",
    "In Progress": "प्रगतीत",
    "View Report": "अहवाल पहा",
    "Download Report": "अहवाल डाउनलोड करा",
    "Preparation before launch": "सुरुवातीपूर्वीची तयारी",
    "Concrete action items to strengthen your entrepreneur readiness before starting.": "सुरू करण्यापूर्वी उद्योजक तयारी मजबूत करण्यासाठी ठोस कृती.",
    "Loading readiness action items...": "तयारीच्या कृती लोड होत आहेत...",
    "Current": "सध्याचे",
    "Potential": "संभाव्य",
    "Potential Preparedness": "संभाव्य तयारी",
    "points gained from completed actions": "पूर्ण कृतींमधून मिळालेले गुण",
    "of": "पैकी",
    "Actions Completed": "कृती पूर्ण",
    "Recommended Action Items": "शिफारस केलेल्या कृती",
    "Readiness": "तयारी",
    "Dimension:": "घटक:",
    "Experience": "अनुभव",
    "Skill": "कौशल्य",
    "Resources": "संसाधने",
    "Complete 2-Week Domain Apprenticeship": "2 आठवड्यांची क्षेत्रीय उमेदवारी पूर्ण करा",
    "Shadow an established shop owner in a nearby town to learn practical daily operations.": "दैनंदिन कामकाज शिकण्यासाठी जवळच्या शहरातील अनुभवी दुकानदाराकडे प्रशिक्षण घ्या.",
    "Enroll in RSETI / Skill India Dairy Training": "आरसेटी / स्किल इंडिया दुग्ध प्रशिक्षणात नाव नोंदवा",
    "Undergo certified technical skill and equipment maintenance training for Dairy.": "दुग्ध व्यवसायासाठी प्रमाणित तांत्रिक कौशल्य आणि उपकरण देखभाल प्रशिक्षण घ्या.",
    "Finalize Workspace Lease Agreement": "कार्यस्थळाचा भाडेकरार अंतिम करा",
    "Secure a roadside workspace location with adequate power fitting and public access.": "पुरेशी वीज आणि सार्वजनिक प्रवेश असलेले रस्त्यालगतचे कार्यस्थळ निश्चित करा.",
    "This reflects improved preparedness, not guaranteed business financial success. The potential score assumes every listed action is completed.": "हे सुधारलेली तयारी दर्शवते; व्यवसायाच्या आर्थिक यशाची हमी नाही. संभाव्य गुण सर्व सूचीबद्ध कृती पूर्ण झाल्याच्या गृहितकावर आहेत.",
    "Business ↔ Person ↔ Location": "व्यवसाय ↔ व्यक्ती ↔ ठिकाण",
    "Demo estimates": "डेमो अंदाज",
    "Ranked comparison of 5 business categories for your village location and capital.": "तुमच्या गावाचे ठिकाण आणि भांडवलानुसार 5 व्यवसाय श्रेणींची क्रमवारीतील तुलना.",
    "Evaluating 5 business alternatives...": "5 व्यवसाय पर्यायांचे मूल्यमापन होत आहे...",
    "Explore This Business →": "हा व्यवसाय पहा →",
    "Strong Fit": "उत्तम योग्यता",
    "Promising": "आशादायक",
    "Moderate": "मध्यम",
    "Weak": "कमकुवत",
    "Poor": "कमकुवत",
    "Good": "चांगली",
    "Dairy": "दुग्ध व्यवसाय",
    "Dairy Farming & Milk Collection": "दुग्धव्यवसाय आणि दूध संकलन",
    "Small-scale Poultry Unit": "लघु कुक्कुटपालन युनिट",
    "Tailoring & Garment Shop": "शिवणकाम आणि कपड्यांचे दुकान",
    "Flour Mill (Atta Chakki)": "पिठाची गिरणी",
    "Two-Wheeler Workshop": "दुचाकी दुरुस्ती कार्यशाळा",
    "Good market demand with moderate setup capital requirement.": "चांगली बाजार मागणी आणि मध्यम स्थापना भांडवलाची आवश्यकता.",
    "Feasible business option but requires capital scale adjustment.": "व्यवहार्य व्यवसाय पर्याय, पण भांडवल पातळीत बदल आवश्यक.",
    "Higher capital barrier or lower demand gap in catchment.": "जास्त भांडवली अडथळा किंवा स्थानिक परिसरात कमी मागणीतील तफावत.",
    "Alternative scores are prototype comparisons for decision support. They do not guarantee business performance.": "पर्यायी गुण निर्णय सहाय्यासाठी प्रोटोटाइप तुलना आहेत. ते व्यवसाय कामगिरीची हमी देत नाहीत.",
    "Financial fit · Demo estimate": "आर्थिक योग्यता · डेमो अंदाज",
    "Scheme matching": "योजना जुळवणी",
    "Government loan scheme details, reducing-balance EMI calculation, and 90-day roadmap.": "सरकारी कर्ज योजनेचे तपशील, घटत्या शिल्लक रकमेवरील ईएमआय गणना आणि 90-दिवसीय आराखडा.",
    "Loading financial plan calculations...": "आर्थिक योजनेची गणना लोड होत आहे...",
    "Your margin": "तुमचे मार्जिन",
    "Project cost": "प्रकल्प खर्च",
    "Indicative loan": "सूचक कर्ज",
    "Indicative scheme": "सूचक योजना",
    "Government tier": "सरकारी श्रेणी",
    "Government Rural Term Loan Scheme": "सरकारी ग्रामीण मुदत कर्ज योजना",
    "Term loan for project setup between ₹1.40 Lakh and ₹50.00 Lakh with 8% interest rate and 6-month moratorium.": "₹1.40 लाख ते ₹50.00 लाख प्रकल्प स्थापना कर्ज, 8% व्याजदर आणि 6 महिन्यांच्या स्थगितीसह.",
    "Interest rate": "व्याजदर",
    "Tenure": "कालावधी",
    "Moratorium period": "स्थगिती कालावधी",
    "Monthly EMI": "मासिक ईएमआय",
    "Years": "वर्षे",
    "Mos": "महिने",
    "Months": "महिने",
    "Scheme terms are illustrative and must be verified at your local bank branch before applying.": "योजनेच्या अटी उदाहरणादाखल आहेत; अर्ज करण्यापूर्वी स्थानिक बँक शाखेत खात्री करा.",
    "Monthly affordability": "मासिक परवड",
    "Safe (<40%)": "सुरक्षित (<40%)",
    "Moderate (40-60%)": "मध्यम (40-60%)",
    "High Risk (>60%)": "उच्च धोका (>60%)",
    "Estimated EMI:": "अंदाजित ईएमआय:",
    "Household Expenses:": "घरगुती खर्च:",
    "This indicator highlights potential debt pressure; it is not loan approval.": "हा निर्देशक संभाव्य कर्जाचा ताण दाखवतो; ही कर्ज मंजुरी नाही.",
    "Know before you borrow": "कर्ज घेण्यापूर्वी जाणून घ्या",
    "Financial Literacy Notes": "आर्थिक साक्षरता नोंदी",
    "What is EMI?": "ईएमआय म्हणजे काय?",
    "Equated Monthly Installment is a fixed monthly payment covering principal and reducing-balance interest.": "समान मासिक हप्ता हा मूळ रक्कम आणि घटत्या शिल्लक रकमेवरील व्याज समाविष्ट करणारा निश्चित मासिक भरणा आहे.",
    "What is a Moratorium?": "स्थगिती कालावधी म्हणजे काय?",
    "A grace period (3 to 6 months) allowing you to set up operations before monthly principal EMI begins.": "3 ते 6 महिन्यांचा सवलत कालावधी, ज्यात मासिक मूळ ईएमआय सुरू होण्यापूर्वी व्यवसाय उभारता येतो.",
    "Repayment Risk": "परतफेडीचा धोका",
    "Keeping total monthly debt payments under 40% of disposable capacity prevents default in low-income months.": "एकूण मासिक कर्ज भरणा उपलब्ध क्षमतेच्या 40% खाली ठेवल्यास कमी उत्पन्नाच्या महिन्यांत थकबाकीचा धोका कमी होतो.",
    "Emergency Reserve": "आपत्कालीन राखीव निधी",
    "Maintain ₹15,000+ liquid reserve to cushion inventory spikes or equipment repairs without missing EMIs.": "ईएमआय न चुकवता साठ्यातील वाढ किंवा उपकरण दुरुस्तीसाठी ₹15,000 पेक्षा जास्त रोख राखीव ठेवा.",
    "Moratorium interest note:": "स्थगिती व्याज नोंद:",
    "From preparation to launch": "तयारीपासून सुरुवातीपर्यंत",
    "90-Day Execution Roadmap": "90-दिवसीय अंमलबजावणी आराखडा",
    "Days 1–30": "दिवस 1–30",
    "Days 31–60": "दिवस 31–60",
    "Days 61–90": "दिवस 61–90",
    "Submit loan application at bank branch.": "बँक शाखेत कर्ज अर्ज सादर करा.",
    "Apply for Udyam MSME & Panchayat NOC.": "उद्यम एमएसएमई आणि पंचायत एनओसीसाठी अर्ज करा.",
    "Secure workspace lease agreement.": "कार्यस्थळाचा भाडेकरार निश्चित करा.",
    "Deposit entrepreneur margin contribution.": "उद्योजक मार्जिन योगदान जमा करा.",
    "Procure machinery & raw material inventory.": "यंत्रसामग्री आणि कच्चा माल खरेदी करा.",
    "Install equipment and test trials.": "उपकरणे बसवून चाचणी घ्या.",
    "Distribute local launch pamphlets.": "स्थानिक प्रचार पत्रके वितरित करा.",
    "Official commercial business launch.": "व्यवसायाचा अधिकृत व्यावसायिक शुभारंभ करा.",
    "Prepare for post-moratorium EMI repayment.": "स्थगितीनंतरच्या ईएमआय परतफेडीची तयारी करा.",
    "Financial calculations are demo estimates. Final loan approval and interest rates depend on bank credit appraisal.": "आर्थिक गणना डेमो अंदाज आहेत. अंतिम कर्ज मंजुरी आणि व्याजदर बँकेच्या पत मूल्यमापनावर अवलंबून आहेत.",
    "Regulatory & aid directory": "नियामक आणि सहाय्य निर्देशिका",
    "Find nearby District Legal Services Authorities and required business registration documents.": "जवळचे जिल्हा विधी सेवा प्राधिकरण आणि आवश्यक व्यवसाय नोंदणी कागदपत्रे शोधा.",
    "Loading nearest legal offices and document checklists...": "जवळची कायदेशीर कार्यालये आणि कागदपत्र सूची लोड होत आहे...",
    "District aid centres": "जिल्हा सहाय्य केंद्रे",
    "Legal & registration support near you": "तुमच्या जवळ कायदेशीर आणि नोंदणी सहाय्य",
    "Contact official legal services authorities for MSME registration and report review.": "एमएसएमई नोंदणी आणि अहवाल पुनरावलोकनासाठी अधिकृत विधी सेवा प्राधिकरणांशी संपर्क साधा.",
    "District Legal Services Authority": "जिल्हा विधी सेवा प्राधिकरण",
    "District Industries Centre": "जिल्हा उद्योग केंद्र",
    "Regulatory compliance": "नियामक अनुपालन",
    "Required identity documents and local government trade licenses.": "आवश्यक ओळख कागदपत्रे आणि स्थानिक सरकारी व्यापार परवाने.",
    "Required Identity & Bank Documents": "आवश्यक ओळख आणि बँक कागदपत्रे",
    "Regulatory & Trade Requirements": "नियामक आणि व्यापार आवश्यकता",
    "report review": "अहवाल पुनरावलोकन",
    "msme registration": "एमएसएमई नोंदणी",
    "general legal aid": "सामान्य कायदेशीर मदत",
    "micro finance counseling": "सूक्ष्म वित्त समुपदेशन",
    "subsidies guidance": "अनुदान मार्गदर्शन",
    "scheme verification": "योजना पडताळणी",
    "Account": "खाते",
    "Manage your personal details, language preferences, and accessibility settings.": "तुमचे वैयक्तिक तपशील, भाषा प्राधान्ये आणि सुलभता सेटिंग्ज व्यवस्थापित करा.",
    "Edit profile": "प्रोफाइल संपादित करा",
    "Cancel editing": "संपादन रद्द करा",
    "Profile Complete": "प्रोफाइल पूर्ण",
    "Profile details": "प्रोफाइल तपशील",
    "Full name": "पूर्ण नाव",
    "Mobile": "मोबाइल",
    "Mobile number": "मोबाइल क्रमांक",
    "Email address": "ईमेल पत्ता",
    "Preferred language": "पसंतीची भाषा",
    "State & district": "राज्य आणि जिल्हा",
    "Preferences & accessibility": "प्राधान्ये आणि सुलभता",
    "App Preferences": "ॲप प्राधान्ये",
    "App language": "ॲपची भाषा",
    "English, Hindi and Marathi supported": "इंग्रजी, हिन्दी आणि मराठी समर्थित आहेत",
    "Accessibility preferences": "सुलभता प्राधान्ये",
    "High-contrast visuals and reduced animation settings": "उच्च-कॉन्ट्रास्ट दृश्ये आणि कमी ॲनिमेशन सेटिंग्ज",
    "High contrast": "उच्च कॉन्ट्रास्ट",
    "Reduced motion": "कमी हालचाल",
    "Sign Out of Account": "खात्यातून साइन आउट करा",
    "Clears active session token from browser local storage.": "ब्राउझरच्या स्थानिक संचयातून सक्रिय सत्र टोकन काढते.",
    "Rural Micro-Entrepreneur": "ग्रामीण सूक्ष्म-उद्योजक",
    "English": "इंग्रजी",
    "Hindi": "हिन्दी",
    "Marathi": "मराठी",
    "Welcome back": "पुन्हा स्वागत आहे",
    "Log in to your account": "तुमच्या खात्यात लॉग इन करा",
    "Password": "पासवर्ड",
    "Remember me": "मला लक्षात ठेवा",
    "Get started": "सुरू करा",
    "Create your account": "तुमचे खाते तयार करा",
    "Confirm password": "पासवर्डची पुष्टी करा",
    "Creating account...": "खाते तयार होत आहे...",
    "Already have an account?": "आधीपासून खाते आहे?",
    "Instant village-level demand analysis": "गाव-पातळीवरील मागणीचे त्वरित विश्लेषण",
    "Readiness preparation action plan": "तयारीची कृती योजना",
    "Local legal office directory & checklists": "स्थानिक कायदेशीर कार्यालय निर्देशिका आणि तपासणी सूची",
    "Catchment legend": "स्थानिक परिसर संकेत",
    "10 km radius circle": "10 किमी त्रिज्या वर्तुळ",
    "Competitor shops": "स्पर्धक दुकाने",
    "Selected Village Center": "निवडलेले गाव केंद्र",
    "Distance:": "अंतर:",
    "We analyse nearby villages, local population, business density, and infrastructure within approximately 10 km for the selected business only.": "आम्ही फक्त निवडलेल्या व्यवसायासाठी सुमारे 10 किमी परिसरातील जवळची गावे, लोकसंख्या, व्यवसाय घनता आणि पायाभूत सुविधांचे विश्लेषण करतो."
  }
};

const ADDITIONAL_TRANSLATIONS = {
  hi: {
    "Step": "चरण", "Profile": "प्रोफ़ाइल", "Business": "व्यवसाय", "Readiness": "तत्परता", "Finance": "वित्त", "Review": "समीक्षा",
    "Step 1 of 5": "चरण 1 / 5", "Step 2 of 5": "चरण 2 / 5", "Step 3 of 5": "चरण 3 / 5", "Step 4 of 5": "चरण 4 / 5", "Step 5 of 5": "चरण 5 / 5",
    "Draft saved": "मसौदा सहेजा गया", "Business Feasibility Assessment": "व्यवसाय व्यवहार्यता मूल्यांकन",
    "Answer a few questions about your background, intended business, and local village location. We evaluate your proposal across Market Feasibility, Entrepreneur Readiness, and Financial Fit before you take on debt.": "अपनी पृष्ठभूमि, प्रस्तावित व्यवसाय और गांव के स्थान के बारे में कुछ प्रश्नों के उत्तर दें। ऋण लेने से पहले हम बाज़ार व्यवहार्यता, उद्यमी तत्परता और वित्तीय उपयुक्तता पर आपके प्रस्ताव का मूल्यांकन करते हैं।",
    "Personal background": "व्यक्तिगत पृष्ठभूमि", "Resources you can use (multi-select)": "उपयोग योग्य संसाधन (एक से अधिक चुनें)",
    "Own land": "अपनी जमीन", "Shop/workspace": "दुकान / कार्यस्थल", "Vehicle": "वाहन", "Electricity": "बिजली", "Storage": "भंडारण", "Machinery/equipment": "मशीनरी / उपकरण", "Family labour": "पारिवारिक श्रम", "Existing customers": "मौजूदा ग्राहक",
    "Select business category": "व्यवसाय श्रेणी चुनें", "Capital:": "पूंजी:", "Target village location": "लक्षित गांव का स्थान",
    "Readiness Questionnaire": "तत्परता प्रश्नावली", "Yes": "हाँ", "No": "नहीं", "Somewhat": "कुछ हद तक",
    "Primary": "प्राथमिक", "Secondary": "माध्यमिक", "Graduate": "स्नातक", "No Formal": "औपचारिक शिक्षा नहीं",
    "Age": "आयु", "experience": "अनुभव", "readiness": "तत्परता", "Available margin:": "उपलब्ध मार्जिन:",
    "Final calculations, reducing balance interest, moratorium period, and exact EMI figures will come from the financial engine when you click Run.": "अंतिम गणना, घटती शेष राशि का ब्याज, स्थगन अवधि और सटीक ईएमआई आंकड़े ‘चलाएं’ दबाने पर वित्तीय इंजन से आएंगे।",
    "Ready to analyse? Our deterministic engines will evaluate 10km village catchment demand, entrepreneur readiness, loan scheme options, and EMI affordability.": "विश्लेषण के लिए तैयार हैं? हमारे निर्धारित इंजन 10 किमी क्षेत्र की मांग, उद्यमी तत्परता, ऋण योजना विकल्प और ईएमआई वहनीयता का मूल्यांकन करेंगे।",
    "Keeping market feasibility, entrepreneur readiness, and financial fit separate for clear explainability.": "स्पष्ट व्याख्या के लिए बाज़ार व्यवहार्यता, उद्यमी तत्परता और वित्तीय उपयुक्तता को अलग रखा गया है।",
    "Analysing local village demographics": "स्थानीय गांव की जनसांख्यिकी का विश्लेषण", "Mapping nearby villages within 10km catchment": "10 किमी क्षेत्र के नज़दीकी गांवों का मानचित्रण", "Evaluating local competitor density": "स्थानीय प्रतिस्पर्धी घनत्व का मूल्यांकन", "Measuring road & power infrastructure signals": "सड़क और बिजली ढांचे के संकेतों का मापन", "Assessing entrepreneur readiness & resources": "उद्यमी तत्परता और संसाधनों का आकलन", "Structuring reducing-balance finance scheme": "घटती शेष राशि वाली वित्त योजना तैयार करना", "Generating plain-language recommendations": "सरल भाषा में सिफारिशें तैयार करना",
    "Do you currently own cattle?": "क्या आपके पास अभी मवेशी हैं?", "How many cattle can you start with?": "आप कितने मवेशियों से शुरुआत कर सकते हैं?", "Do you have a reliable fodder source?": "क्या आपके पास चारे का विश्वसनीय स्रोत है?", "Is adequate water available year-round?": "क्या पूरे वर्ष पर्याप्त पानी उपलब्ध है?", "Do you have access to refrigeration?": "क्या आपके पास शीत भंडारण की सुविधा है?", "Is there a milk collection centre nearby?": "क्या पास में दूध संग्रह केंद्र है?", "How many reliable buyers have you identified?": "आपने कितने विश्वसनीय खरीदार पहचाने हैं?",
    "Understand the opportunity before you commit your savings or take a loan.": "अपनी बचत लगाने या ऋण लेने से पहले अवसर को समझें।", "Deterministic 3-way fit scoring": "निर्धारित 3-तरफा उपयुक्तता स्कोर", "Village-level market & competition mapping": "गांव-स्तरीय बाज़ार और प्रतिस्पर्धा मानचित्रण", "Reducing-balance EMI & scheme matching": "घटती शेष राशि वाली ईएमआई और योजना मिलान", "Access your saved assessments, improvement plans, and legal advice.": "अपने सहेजे गए मूल्यांकन, सुधार योजनाएं और कानूनी सलाह देखें।", "Demo Tip:": "डेमो सुझाव:", "Create a new account via Signup, or log in with any existing registered user credentials.": "साइन अप करके नया खाता बनाएं या किसी पंजीकृत उपयोगकर्ता के विवरण से लॉग इन करें।", "Forgot password?": "पासवर्ड भूल गए?", "Logging in...": "लॉग इन हो रहा है...", "Don't have an account yet?": "अभी तक खाता नहीं है?",
    "Create your account to start evaluating business ideas.": "व्यवसाय विचारों का मूल्यांकन शुरू करने के लिए खाता बनाएं।", "Enter your details to generate personalized feasibility reports.": "व्यक्तिगत व्यवहार्यता रिपोर्ट बनाने के लिए अपना विवरण दर्ज करें।", "Saving...": "सहेजा जा रहा है...",
    "Loading full feasibility report payload...": "पूरी व्यवहार्यता रिपोर्ट लोड हो रही है...", "Assessment report not found.": "मूल्यांकन रिपोर्ट नहीं मिली।", "Focused assessment": "केंद्रित मूल्यांकन", "Business Feasibility Report": "व्यवसाय व्यवहार्यता रिपोर्ट", "Proceed after preparation": "तैयारी के बाद आगे बढ़ें", "Proceed after preparation — Good Feasibility": "तैयारी के बाद आगे बढ़ें — अच्छी व्यवहार्यता", "Your business feasibility rating is derived from a 3-way fit analysis.": "आपकी व्यवसाय व्यवहार्यता रेटिंग 3-तरफा उपयुक्तता विश्लेषण से तैयार की गई है।",
    "Weight": "भार", "10km radius demand, competitor density & roads.": "10 किमी क्षेत्र की मांग, प्रतिस्पर्धी घनत्व और सड़कें।", "Skills, workspace, supplier links & customers.": "कौशल, कार्यस्थल, आपूर्तिकर्ता संपर्क और ग्राहक।", "Margin capital coverage & monthly EMI capacity.": "मार्जिन पूंजी कवरेज और मासिक ईएमआई क्षमता।", "Explainability summary": "व्याख्या सारांश", "Why this score?": "यह स्कोर क्यों?", "Supports this business": "इस व्यवसाय के पक्ष में", "Needs attention": "ध्यान देने की जरूरत",
    "10 km catchment radius": "10 किमी स्थानीय क्षेत्र", "Hyper-local market picture": "अति-स्थानीय बाज़ार चित्र", "Competitor pressure:": "प्रतिस्पर्धी दबाव:", "Low": "कम", "High": "उच्च", "Fair": "सामान्य", "Available": "उपलब्ध", "Nearby": "नज़दीक", "Villages": "गांव", "Population": "जनसंख्या", "Households": "परिवार", "Workers": "कामगार", "Competitors": "प्रतिस्पर्धी", "Nearby competitors": "नज़दीकी प्रतिस्पर्धी",
    "Market demand": "बाज़ार मांग", "Demand & Supply": "मांग और आपूर्ति", "Daily Demand:": "दैनिक मांग:", "Local Supply Gap:": "स्थानीय आपूर्ति अंतर:", "Repeat Purchase:": "दोबारा खरीद:", "Infrastructure": "बुनियादी ढांचा", "Infrastructure Signals": "बुनियादी ढांचे के संकेत", "Road Connectivity:": "सड़क संपर्क:", "Power Access:": "बिजली उपलब्धता:", "Bank Branch:": "बैंक शाखा:", "Data evidence": "डेटा प्रमाण", "Evidence Confidence": "प्रमाण विश्वसनीयता", "Confidence reflects dataset coverage—not business success probability.": "विश्वसनीयता डेटा कवरेज दर्शाती है—व्यवसाय सफलता की संभावना नहीं।", "Strategic analysis": "रणनीतिक विश्लेषण", "SWOT Analysis": "स्वॉट विश्लेषण", "6 dimensions": "6 आयाम", "Entrepreneur Readiness Breakdown": "उद्यमी तत्परता विवरण", "Education is intentionally not scored or used to reduce readiness.": "शिक्षा को जानबूझकर स्कोर नहीं किया जाता और इससे तत्परता कम नहीं होती।", "Domain Experience": "क्षेत्रीय अनुभव", "Technical Skill": "तकनीकी कौशल", "Workspace & Resources": "कार्यस्थल और संसाधन", "Supplier Linkages": "आपूर्तिकर्ता संपर्क", "Customer Commitments": "ग्राहक प्रतिबद्धताएं", "Financial Preparedness": "वित्तीय तैयारी", "Action items to raise your readiness score.": "तत्परता स्कोर बढ़ाने के कार्य।", "Ranked 5 category comparisons for your village.": "आपके गांव के लिए 5 श्रेणियों की क्रमबद्ध तुलना।", "Scheme details, EMI calculation & 90-day plan.": "योजना विवरण, ईएमआई गणना और 90-दिवसीय योजना।", "Nearest legal offices & document checklist.": "नज़दीकी कानूनी कार्यालय और दस्तावेज़ सूची।",
    "Total Assessments": "कुल मूल्यांकन", "Start your first business feasibility assessment to evaluate local village demand, readiness, and loan EMI affordability.": "स्थानीय गांव की मांग, तत्परता और ऋण ईएमआई वहनीयता जांचने के लिए पहला व्यवसाय व्यवहार्यता मूल्यांकन शुरू करें।", "Decision dashboard": "निर्णय डैशबोर्ड",
    "Interest of": "ब्याज", "accrues during the": "इस दौरान जुड़ता है:", "month moratorium and is capitalized into your principal prior to EMI calculation.": "महीने की स्थगन अवधि; ईएमआई गणना से पहले इसे मूलधन में जोड़ा जाता है।", "District Office": "जिला कार्यालय", "Documents you'll need to register": "पंजीकरण के लिए आवश्यक दस्तावेज़:", "Business": "व्यवसाय"
  },
  mr: {
    "Step": "टप्पा", "Profile": "प्रोफाइल", "Business": "व्यवसाय", "Readiness": "तयारी", "Finance": "अर्थव्यवस्था", "Review": "पुनरावलोकन",
    "Step 1 of 5": "टप्पा 1 / 5", "Step 2 of 5": "टप्पा 2 / 5", "Step 3 of 5": "टप्पा 3 / 5", "Step 4 of 5": "टप्पा 4 / 5", "Step 5 of 5": "टप्पा 5 / 5",
    "Draft saved": "मसुदा जतन झाला", "Business Feasibility Assessment": "व्यवसाय व्यवहार्यता मूल्यमापन", "Answer a few questions about your background, intended business, and local village location. We evaluate your proposal across Market Feasibility, Entrepreneur Readiness, and Financial Fit before you take on debt.": "तुमची पार्श्वभूमी, नियोजित व्यवसाय आणि गावाच्या ठिकाणाबद्दल काही प्रश्नांची उत्तरे द्या. कर्ज घेण्यापूर्वी आम्ही बाजार व्यवहार्यता, उद्योजक तयारी आणि आर्थिक योग्यता यांवर प्रस्तावाचे मूल्यमापन करतो.",
    "Personal background": "वैयक्तिक पार्श्वभूमी", "Resources you can use (multi-select)": "वापरता येणारी संसाधने (एकापेक्षा अधिक निवडा)", "Own land": "स्वतःची जमीन", "Shop/workspace": "दुकान / कार्यस्थळ", "Vehicle": "वाहन", "Electricity": "वीज", "Storage": "साठवण", "Machinery/equipment": "यंत्रसामग्री / उपकरणे", "Family labour": "कौटुंबिक श्रम", "Existing customers": "विद्यमान ग्राहक", "Select business category": "व्यवसाय श्रेणी निवडा", "Capital:": "भांडवल:", "Target village location": "लक्षित गावाचे ठिकाण", "Readiness Questionnaire": "तयारी प्रश्नावली", "Yes": "होय", "No": "नाही", "Somewhat": "काही प्रमाणात", "Primary": "प्राथमिक", "Secondary": "माध्यमिक", "Graduate": "पदवीधर", "No Formal": "औपचारिक शिक्षण नाही", "Age": "वय", "experience": "अनुभव", "readiness": "तयारी", "Available margin:": "उपलब्ध मार्जिन:",
    "Final calculations, reducing balance interest, moratorium period, and exact EMI figures will come from the financial engine when you click Run.": "अंतिम गणना, घटत्या शिल्लक रकमेवरील व्याज, स्थगिती कालावधी आणि अचूक ईएमआय आकडे ‘चालवा’ दाबल्यावर आर्थिक इंजिनमधून मिळतील.", "Ready to analyse? Our deterministic engines will evaluate 10km village catchment demand, entrepreneur readiness, loan scheme options, and EMI affordability.": "विश्लेषणासाठी तयार आहात? आमची निश्चित इंजिने 10 किमी परिसराची मागणी, उद्योजक तयारी, कर्ज योजना पर्याय आणि ईएमआय परवड तपासतील.", "Keeping market feasibility, entrepreneur readiness, and financial fit separate for clear explainability.": "स्पष्ट स्पष्टीकरणासाठी बाजार व्यवहार्यता, उद्योजक तयारी आणि आर्थिक योग्यता वेगळी ठेवली आहे.",
    "Analysing local village demographics": "स्थानिक गावाच्या लोकसंख्येचे विश्लेषण", "Mapping nearby villages within 10km catchment": "10 किमी परिसरातील गावांचे नकाशांकन", "Evaluating local competitor density": "स्थानिक स्पर्धक घनतेचे मूल्यमापन", "Measuring road & power infrastructure signals": "रस्ते आणि वीज सुविधांचे मापन", "Assessing entrepreneur readiness & resources": "उद्योजक तयारी आणि संसाधनांचे मूल्यमापन", "Structuring reducing-balance finance scheme": "घटत्या शिल्लक रकमेची वित्त योजना तयार करणे", "Generating plain-language recommendations": "सोप्या भाषेत शिफारसी तयार करणे",
    "Do you currently own cattle?": "तुमच्याकडे सध्या गुरे आहेत का?", "How many cattle can you start with?": "तुम्ही किती गुरांपासून सुरुवात करू शकता?", "Do you have a reliable fodder source?": "तुमच्याकडे चाऱ्याचा विश्वसनीय स्रोत आहे का?", "Is adequate water available year-round?": "वर्षभर पुरेसे पाणी उपलब्ध आहे का?", "Do you have access to refrigeration?": "तुमच्याकडे शीतकरण सुविधा आहे का?", "Is there a milk collection centre nearby?": "जवळ दूध संकलन केंद्र आहे का?", "How many reliable buyers have you identified?": "तुम्ही किती विश्वसनीय खरेदीदार ओळखले आहेत?",
    "Understand the opportunity before you commit your savings or take a loan.": "बचत गुंतवण्यापूर्वी किंवा कर्ज घेण्यापूर्वी संधी समजून घ्या.", "Deterministic 3-way fit scoring": "निश्चित 3-मार्ग योग्यता गुणांकन", "Village-level market & competition mapping": "गाव-पातळीवरील बाजार आणि स्पर्धा नकाशांकन", "Reducing-balance EMI & scheme matching": "घटत्या शिल्लक रकमेची ईएमआय आणि योजना जुळवणी", "Access your saved assessments, improvement plans, and legal advice.": "जतन केलेली मूल्यमापने, सुधारणा योजना आणि कायदेशीर सल्ला पहा.", "Demo Tip:": "डेमो सूचना:", "Create a new account via Signup, or log in with any existing registered user credentials.": "साइन अप करून नवीन खाते तयार करा किंवा नोंदणीकृत वापरकर्त्याच्या तपशीलाने लॉग इन करा.", "Forgot password?": "पासवर्ड विसरलात?", "Logging in...": "लॉग इन होत आहे...", "Don't have an account yet?": "अजून खाते नाही?", "Create your account to start evaluating business ideas.": "व्यवसाय कल्पनांचे मूल्यमापन सुरू करण्यासाठी खाते तयार करा.", "Enter your details to generate personalized feasibility reports.": "वैयक्तिक व्यवहार्यता अहवाल तयार करण्यासाठी तपशील भरा.", "Saving...": "जतन होत आहे...",
    "Loading full feasibility report payload...": "पूर्ण व्यवहार्यता अहवाल लोड होत आहे...", "Assessment report not found.": "मूल्यमापन अहवाल सापडला नाही.", "Focused assessment": "केंद्रित मूल्यमापन", "Business Feasibility Report": "व्यवसाय व्यवहार्यता अहवाल", "Proceed after preparation": "तयारीनंतर पुढे जा", "Proceed after preparation — Good Feasibility": "तयारीनंतर पुढे जा — चांगली व्यवहार्यता", "Your business feasibility rating is derived from a 3-way fit analysis.": "तुमचे व्यवसाय व्यवहार्यता रेटिंग 3-मार्ग योग्यता विश्लेषणातून तयार झाले आहे.",
    "Weight": "भार", "10km radius demand, competitor density & roads.": "10 किमी परिसराची मागणी, स्पर्धक घनता आणि रस्ते.", "Skills, workspace, supplier links & customers.": "कौशल्ये, कार्यस्थळ, पुरवठादार संपर्क आणि ग्राहक.", "Margin capital coverage & monthly EMI capacity.": "मार्जिन भांडवल कव्हरेज आणि मासिक ईएमआय क्षमता.", "Explainability summary": "स्पष्टीकरण सारांश", "Why this score?": "हे गुण का?", "Supports this business": "या व्यवसायाच्या बाजूने", "Needs attention": "लक्ष देण्याची गरज", "10 km catchment radius": "10 किमी स्थानिक परिसर", "Hyper-local market picture": "अतिस्थानिक बाजार चित्र", "Competitor pressure:": "स्पर्धक दबाव:", "Low": "कमी", "High": "उच्च", "Fair": "सामान्य", "Available": "उपलब्ध", "Nearby": "जवळ", "Villages": "गावे", "Population": "लोकसंख्या", "Households": "कुटुंबे", "Workers": "कामगार", "Competitors": "स्पर्धक", "Nearby competitors": "जवळचे स्पर्धक",
    "Market demand": "बाजार मागणी", "Demand & Supply": "मागणी आणि पुरवठा", "Daily Demand:": "दैनिक मागणी:", "Local Supply Gap:": "स्थानिक पुरवठा तफावत:", "Repeat Purchase:": "पुनर्खरेदी:", "Infrastructure": "पायाभूत सुविधा", "Infrastructure Signals": "पायाभूत सुविधा संकेत", "Road Connectivity:": "रस्ता संपर्क:", "Power Access:": "वीज उपलब्धता:", "Bank Branch:": "बँक शाखा:", "Data evidence": "डेटा पुरावा", "Evidence Confidence": "पुरावा विश्वासार्हता", "Confidence reflects dataset coverage—not business success probability.": "विश्वासार्हता डेटा कव्हरेज दर्शवते—व्यवसाय यशाची शक्यता नाही.", "Strategic analysis": "धोरणात्मक विश्लेषण", "SWOT Analysis": "स्वॉट विश्लेषण", "6 dimensions": "6 घटक", "Entrepreneur Readiness Breakdown": "उद्योजक तयारीचे तपशील", "Education is intentionally not scored or used to reduce readiness.": "शिक्षणाला मुद्दाम गुण दिले जात नाहीत आणि त्यामुळे तयारी कमी होत नाही.", "Domain Experience": "क्षेत्रीय अनुभव", "Technical Skill": "तांत्रिक कौशल्य", "Workspace & Resources": "कार्यस्थळ आणि संसाधने", "Supplier Linkages": "पुरवठादार संपर्क", "Customer Commitments": "ग्राहक वचनबद्धता", "Financial Preparedness": "आर्थिक तयारी", "Action items to raise your readiness score.": "तयारीचे गुण वाढवण्यासाठी कृती.", "Ranked 5 category comparisons for your village.": "तुमच्या गावासाठी 5 श्रेणींची क्रमवारीतील तुलना.", "Scheme details, EMI calculation & 90-day plan.": "योजना तपशील, ईएमआय गणना आणि 90-दिवसीय योजना.", "Nearest legal offices & document checklist.": "जवळची कायदेशीर कार्यालये आणि कागदपत्र सूची.",
    "Total Assessments": "एकूण मूल्यमापने", "Start your first business feasibility assessment to evaluate local village demand, readiness, and loan EMI affordability.": "स्थानिक गावाची मागणी, तयारी आणि कर्ज ईएमआय परवड तपासण्यासाठी पहिले व्यवसाय व्यवहार्यता मूल्यमापन सुरू करा.", "Decision dashboard": "निर्णय डॅशबोर्ड", "Interest of": "व्याज", "accrues during the": "या काळात जमा होते:", "month moratorium and is capitalized into your principal prior to EMI calculation.": "महिन्यांच्या स्थगितीत; ईएमआय गणनेपूर्वी ते मूळ रकमेत जोडले जाते.", "District Office": "जिल्हा कार्यालय", "Documents you'll need to register": "नोंदणीसाठी आवश्यक कागदपत्रे:", "Business": "व्यवसाय"
  }
};

const API_FRAGMENT_TRANSLATIONS = {
  hi: {
    "Poultry": "पोल्ट्री", "Tailoring": "सिलाई", "Flour Mill": "आटा चक्की", "Two-Wheeler Repair": "दोपहिया मरम्मत",
    "Proceed — High Feasibility": "आगे बढ़ें — उच्च व्यवहार्यता", "Reconsider scale / business model — Moderate Risk": "व्यवसाय का आकार / मॉडल दोबारा सोचें — मध्यम जोखिम", "Consider alternatives — High Operational Risk": "विकल्पों पर विचार करें — उच्च परिचालन जोखिम", "Borrowing not recommended currently — High Financial Risk": "फिलहाल ऋण लेने की सलाह नहीं — उच्च वित्तीय जोखिम", "Strong": "मजबूत", "High financial risk": "उच्च वित्तीय जोखिम",
    "Your": "आपके", "feasibility is rated": "व्यवहार्यता का आकलन है", "Key strengths include": "मुख्य मजबूत पक्ष हैं", "To maximize success, focus on addressing": "सफलता बढ़ाने के लिए इन बिंदुओं पर ध्यान दें", "before starting operations.": "व्यवसाय शुरू करने से पहले।",
    "High local market demand detected for": "इसके लिए उच्च स्थानीय बाज़ार मांग मिली:", "Moderate/Low local demand demand signal for": "इसके लिए मध्यम/कम स्थानीय मांग का संकेत:", "Low local competitor density within 5km radius.": "5 किमी के भीतर प्रतिस्पर्धियों का घनत्व कम है।", "Manageable competition present within catchment radius.": "स्थानीय क्षेत्र में प्रतिस्पर्धा संभालने योग्य है।", "Significant existing competitor density within 2-5km radius.": "2–5 किमी के भीतर प्रतिस्पर्धियों का घनत्व अधिक है।", "High local supply gap identified; unmet customer demand.": "स्थानीय आपूर्ति में बड़ा अंतर है; ग्राहक मांग पूरी नहीं हो रही।", "Lower average household purchasing power in catchment.": "स्थानीय क्षेत्र में परिवारों की औसत क्रय शक्ति कम है।", "Good road connectivity and accessible village market location.": "अच्छा सड़क संपर्क और सुलभ ग्रामीण बाज़ार स्थान।", "Road/market access constraints present.": "सड़क/बाज़ार पहुंच में बाधाएं हैं।", "Cold chain infrastructure accessible.": "कोल्ड-चेन सुविधा उपलब्ध है।", "Local banking branch present in village.": "गांव में स्थानीय बैंक शाखा मौजूद है।",
    "year(s) of relevant business experience.": "वर्ष का संबंधित व्यवसाय अनुभव।", "First-time entrepreneur with under 1 year domain experience.": "पहली बार उद्यम शुरू कर रहे हैं और क्षेत्रीय अनुभव 1 वर्ष से कम है।", "Possesses core technical/operational skills for business execution.": "व्यवसाय संचालन के लिए आवश्यक तकनीकी/परिचालन कौशल मौजूद हैं।", "Skills training or apprentice period recommended before starting.": "शुरू करने से पहले कौशल प्रशिक्षण या प्रशिक्षुता की सलाह है।", "Workspace / land location already identified and secured.": "कार्यस्थल / जमीन की पहचान कर सुरक्षित कर ली गई है।", "Workspace not yet secured; shop rental required.": "कार्यस्थल अभी सुनिश्चित नहीं; दुकान किराए पर लेनी होगी।", "Established contacts with raw material/equipment suppliers.": "कच्चे माल/उपकरण आपूर्तिकर्ताओं से संपर्क स्थापित हैं।", "No confirmed raw material suppliers established yet.": "कच्चे माल का कोई पुष्ट आपूर्तिकर्ता अभी तय नहीं है।", "Initial customer commitments / buyer linkages confirmed.": "प्रारंभिक ग्राहक प्रतिबद्धताएं / खरीदार संपर्क पुष्ट हैं।", "No pre-committed customers identified yet.": "अभी कोई पूर्व-प्रतिबद्ध ग्राहक नहीं मिला है।", "Emergency cash reserve of": "आपातकालीन नकद आरक्षित राशि", "Limited or zero emergency cash buffer reserve.": "आपातकालीन नकद आरक्षित राशि सीमित या शून्य है।", "Estimated EMI fits comfortably within projected monthly disposable capacity.": "अनुमानित ईएमआई मासिक उपलब्ध क्षमता में आराम से समाती है।", "EMI is manageable but tight relative to monthly household expenses.": "ईएमआई संभाली जा सकती है, लेकिन मासिक घरेलू खर्च की तुलना में दबावपूर्ण है।", "High debt burden ratio (>60%). Risk of loan default under income stress.": "ऋण भार अनुपात उच्च (>60%) है; आय दबाव में चूक का जोखिम है।",
    "demonstrates strong local market demand in the village with excellent capital alignment.": "गांव में मजबूत स्थानीय मांग और पूंजी के साथ उत्कृष्ट तालमेल दिखाता है।", "offers good local demand opportunity, though requiring moderate capital setup adjustment.": "अच्छी स्थानीय मांग का अवसर देता है, हालांकि स्थापना पूंजी में मध्यम बदलाव आवश्यक है।", "represents a viable secondary alternative requiring higher setup capital or specialized skills.": "एक व्यवहार्य वैकल्पिक विकल्प है, जिसके लिए अधिक स्थापना पूंजी या विशेष कौशल चाहिए।",
    "Confirm 2 Wholesale Supplier Links": "2 थोक आपूर्तिकर्ता संपर्क पुष्ट करें", "Establish written price quotations and supply delivery commitments with raw material distributors.": "कच्चा माल वितरकों से लिखित मूल्य-कोटेशन और आपूर्ति प्रतिबद्धता लें।", "Gather Pre-orders & Buyer Letters": "पूर्व-ऑर्डर और खरीदार पत्र जुटाएं", "Secure initial customer commitments or buyer intent letters from local households.": "स्थानीय परिवारों से प्रारंभिक ग्राहक प्रतिबद्धता या खरीद आशय पत्र लें।", "Build ₹15,000 Emergency Cash Reserve": "₹15,000 की आपातकालीन नकद निधि बनाएं", "Deposit emergency cash buffer in a liquid bank savings account prior to loan disbursement.": "ऋण वितरण से पहले आपातकालीन नकद राशि बचत खाते में जमा करें।", "Supplier": "आपूर्तिकर्ता", "Customer": "ग्राहक", "Financial Preparedness": "वित्तीय तैयारी",
    "District Legal Services Authority, Pune": "जिला विधिक सेवा प्राधिकरण, पुणे", "District Industries Centre (DIC), Pune": "जिला उद्योग केंद्र (डीआईसी), पुणे",
    "Aadhaar Card & PAN Card of Applicant": "आवेदक का आधार कार्ड और पैन कार्ड", "Proof of Land / Workspace Ownership or Lease Agreement": "जमीन / कार्यस्थल के स्वामित्व का प्रमाण या पट्टा समझौता", "Bank Account Passbook (last 6 months statement)": "बैंक खाता पासबुक (पिछले 6 महीने का विवरण)", "Voter ID / Ration Card for Residence Proof": "निवास प्रमाण के लिए मतदाता पहचान पत्र / राशन कार्ड", "Cattle Breed & Health Clearance Certificate from Local Veterinary Doctor": "स्थानीय पशु चिकित्सक से पशु नस्ल और स्वास्थ्य प्रमाणपत्र", "Udyam MSME Registration Certificate": "उद्यम एमएसएमई पंजीकरण प्रमाणपत्र", "Local Gram Panchayat No Objection Certificate (NOC) for animal shed setup": "पशु शेड के लिए स्थानीय ग्राम पंचायत अनापत्ति प्रमाणपत्र (एनओसी)", "FSSAI Food Safety License (if selling processed milk or milk products directly)": "एफएसएसएआई खाद्य सुरक्षा लाइसेंस (यदि प्रसंस्कृत दूध या दुग्ध उत्पाद सीधे बेचें)",
    "Legal advice and document checklists are for informational support. Verify exact registration steps with local District Industries Centres.": "कानूनी सलाह और दस्तावेज़ सूची केवल जानकारी के लिए हैं। पंजीकरण के सटीक चरण स्थानीय जिला उद्योग केंद्र से जांचें।"
  },
  mr: {
    "Poultry": "कुक्कुटपालन", "Tailoring": "शिवणकाम", "Flour Mill": "पिठाची गिरणी", "Two-Wheeler Repair": "दुचाकी दुरुस्ती",
    "Proceed — High Feasibility": "पुढे जा — उच्च व्यवहार्यता", "Reconsider scale / business model — Moderate Risk": "व्यवसायाचा आकार / मॉडेल पुन्हा विचारात घ्या — मध्यम धोका", "Consider alternatives — High Operational Risk": "पर्यायांचा विचार करा — उच्च कार्यकारी धोका", "Borrowing not recommended currently — High Financial Risk": "सध्या कर्ज घेण्याची शिफारस नाही — उच्च आर्थिक धोका", "Strong": "मजबूत", "High financial risk": "उच्च आर्थिक धोका",
    "Your": "तुमच्या", "feasibility is rated": "व्यवहार्यतेचे मूल्यमापन आहे", "Key strengths include": "मुख्य सामर्थ्ये आहेत", "To maximize success, focus on addressing": "यश वाढवण्यासाठी या बाबींवर लक्ष द्या", "before starting operations.": "व्यवसाय सुरू करण्यापूर्वी.",
    "High local market demand detected for": "यासाठी उच्च स्थानिक बाजार मागणी आढळली:", "Moderate/Low local demand demand signal for": "यासाठी मध्यम/कमी स्थानिक मागणीचा संकेत:", "Low local competitor density within 5km radius.": "5 किमी परिसरात स्पर्धकांची घनता कमी आहे.", "Manageable competition present within catchment radius.": "स्थानिक परिसरातील स्पर्धा हाताळण्याजोगी आहे.", "Significant existing competitor density within 2-5km radius.": "2–5 किमी परिसरात स्पर्धकांची घनता जास्त आहे.", "High local supply gap identified; unmet customer demand.": "स्थानिक पुरवठ्यात मोठी तफावत आहे; ग्राहकांची मागणी अपूर्ण आहे.", "Lower average household purchasing power in catchment.": "स्थानिक परिसरातील कुटुंबांची सरासरी क्रयशक्ती कमी आहे.", "Good road connectivity and accessible village market location.": "चांगला रस्ता संपर्क आणि सहज उपलब्ध गाव बाजार.", "Road/market access constraints present.": "रस्ता/बाजार प्रवेशात अडचणी आहेत.", "Cold chain infrastructure accessible.": "कोल्ड-चेन सुविधा उपलब्ध आहे.", "Local banking branch present in village.": "गावात स्थानिक बँक शाखा आहे.",
    "year(s) of relevant business experience.": "वर्षांचा संबंधित व्यवसाय अनुभव.", "First-time entrepreneur with under 1 year domain experience.": "प्रथमच व्यवसाय सुरू करत आहेत आणि क्षेत्रीय अनुभव 1 वर्षापेक्षा कमी आहे.", "Possesses core technical/operational skills for business execution.": "व्यवसायासाठी आवश्यक तांत्रिक/कार्यकारी कौशल्ये आहेत.", "Skills training or apprentice period recommended before starting.": "सुरू करण्यापूर्वी कौशल्य प्रशिक्षण किंवा उमेदवारीची शिफारस आहे.", "Workspace / land location already identified and secured.": "कार्यस्थळ / जमिनीचे ठिकाण ओळखून सुरक्षित केले आहे.", "Workspace not yet secured; shop rental required.": "कार्यस्थळ अजून निश्चित नाही; दुकान भाड्याने घ्यावे लागेल.", "Established contacts with raw material/equipment suppliers.": "कच्चा माल/उपकरण पुरवठादारांशी संपर्क स्थापित आहेत.", "No confirmed raw material suppliers established yet.": "कच्च्या मालाचा कोणताही निश्चित पुरवठादार अजून ठरलेला नाही.", "Initial customer commitments / buyer linkages confirmed.": "प्रारंभिक ग्राहक वचनबद्धता / खरेदीदार संपर्क निश्चित आहेत.", "No pre-committed customers identified yet.": "अजून कोणतेही पूर्व-वचनबद्ध ग्राहक ओळखलेले नाहीत.", "Emergency cash reserve of": "आपत्कालीन रोख राखीव रक्कम", "Limited or zero emergency cash buffer reserve.": "आपत्कालीन रोख राखीव रक्कम मर्यादित किंवा शून्य आहे.", "Estimated EMI fits comfortably within projected monthly disposable capacity.": "अंदाजित ईएमआय मासिक उपलब्ध क्षमतेत सहज बसते.", "EMI is manageable but tight relative to monthly household expenses.": "ईएमआय हाताळण्याजोगी आहे, पण मासिक घरखर्चाच्या तुलनेत ताणाची आहे.", "High debt burden ratio (>60%). Risk of loan default under income stress.": "कर्जभार प्रमाण उच्च (>60%) आहे; उत्पन्न ताणात थकबाकीचा धोका आहे.",
    "demonstrates strong local market demand in the village with excellent capital alignment.": "गावात मजबूत स्थानिक मागणी आणि भांडवलाशी उत्कृष्ट जुळवणी दर्शवतो.", "offers good local demand opportunity, though requiring moderate capital setup adjustment.": "चांगल्या स्थानिक मागणीची संधी देतो, मात्र स्थापना भांडवलात मध्यम बदल आवश्यक आहे.", "represents a viable secondary alternative requiring higher setup capital or specialized skills.": "अधिक स्थापना भांडवल किंवा विशेष कौशल्ये आवश्यक असलेला व्यवहार्य दुय्यम पर्याय आहे.",
    "Confirm 2 Wholesale Supplier Links": "2 घाऊक पुरवठादार संपर्क निश्चित करा", "Establish written price quotations and supply delivery commitments with raw material distributors.": "कच्चा माल वितरकांकडून लेखी किंमतपत्रे आणि पुरवठा वचनबद्धता घ्या.", "Gather Pre-orders & Buyer Letters": "पूर्व-ऑर्डर आणि खरेदीदार पत्रे मिळवा", "Secure initial customer commitments or buyer intent letters from local households.": "स्थानिक कुटुंबांकडून प्रारंभिक ग्राहक वचनबद्धता किंवा खरेदी आशयपत्रे घ्या.", "Build ₹15,000 Emergency Cash Reserve": "₹15,000 आपत्कालीन रोख निधी तयार करा", "Deposit emergency cash buffer in a liquid bank savings account prior to loan disbursement.": "कर्ज वितरणापूर्वी आपत्कालीन रोख रक्कम बचत खात्यात जमा करा.", "Supplier": "पुरवठादार", "Customer": "ग्राहक", "Financial Preparedness": "आर्थिक तयारी",
    "District Legal Services Authority, Pune": "जिल्हा विधी सेवा प्राधिकरण, पुणे", "District Industries Centre (DIC), Pune": "जिल्हा उद्योग केंद्र (डीआयसी), पुणे",
    "Aadhaar Card & PAN Card of Applicant": "अर्जदाराचे आधार कार्ड आणि पॅन कार्ड", "Proof of Land / Workspace Ownership or Lease Agreement": "जमीन / कार्यस्थळ मालकीचा पुरावा किंवा भाडेकरार", "Bank Account Passbook (last 6 months statement)": "बँक खाते पासबुक (मागील 6 महिन्यांचे विवरण)", "Voter ID / Ration Card for Residence Proof": "रहिवासी पुराव्यासाठी मतदार ओळखपत्र / रेशन कार्ड", "Cattle Breed & Health Clearance Certificate from Local Veterinary Doctor": "स्थानिक पशुवैद्यकाकडून गुरांची जात आणि आरोग्य प्रमाणपत्र", "Udyam MSME Registration Certificate": "उद्यम एमएसएमई नोंदणी प्रमाणपत्र", "Local Gram Panchayat No Objection Certificate (NOC) for animal shed setup": "जनावरांच्या शेडसाठी स्थानिक ग्रामपंचायत ना-हरकत प्रमाणपत्र (एनओसी)", "FSSAI Food Safety License (if selling processed milk or milk products directly)": "एफएसएसएआय अन्न सुरक्षा परवाना (प्रक्रिया केलेले दूध किंवा दुग्धजन्य पदार्थ थेट विकल्यास)",
    "Legal advice and document checklists are for informational support. Verify exact registration steps with local District Industries Centres.": "कायदेशीर सल्ला आणि कागदपत्र सूची फक्त माहितीसाठी आहेत. नोंदणीचे अचूक टप्पे स्थानिक जिल्हा उद्योग केंद्रात तपासा."
  }
};

const SHARED_TRANSLATIONS = {
  hi: {
    "Prototype": "प्रोटोटाइप", "Rural Feasibility & Literacy": "ग्रामीण व्यवहार्यता और साक्षरता", "Recommendations use prototype data and do not guarantee business success.": "सिफारिशें प्रोटोटाइप डेटा पर आधारित हैं और व्यवसाय की सफलता की गारंटी नहीं देतीं।",
    "Three-way fit analysis": "3-तरफा उपयुक्तता विश्लेषण", "1. Business ↔ Location": "1. व्यवसाय ↔ स्थान", "Market feasibility & local demand": "बाज़ार व्यवहार्यता और स्थानीय मांग", "2. Person ↔ Business": "2. व्यक्ति ↔ व्यवसाय", "Entrepreneur readiness & resources": "उद्यमी तत्परता और संसाधन", "3. Person ↔ Finance": "3. व्यक्ति ↔ वित्त", "Financial fit & debt capacity": "वित्तीय उपयुक्तता और ऋण क्षमता", "Converges into": "परिणाम", "Better Decision": "बेहतर निर्णय",
    "Category profile": "श्रेणी प्रोफ़ाइल", "Capital requirement:": "पूंजी आवश्यकता:", "Demand drivers": "मांग के कारक", "Supply signals": "आपूर्ति संकेत", "Risk factors": "जोखिम कारक", "Loading business category details...": "व्यवसाय श्रेणी का विवरण लोड हो रहा है...", "Close Profile": "प्रोफ़ाइल बंद करें",
    "Side-by-side comparison": "साथ-साथ तुलना", "Compare Past Assessments": "पिछले मूल्यांकनों की तुलना", "Assessment A": "मूल्यांकन A", "Assessment B": "मूल्यांकन B", "Market Score:": "बाज़ार स्कोर:", "Readiness Score:": "तत्परता स्कोर:", "Financial Score:": "वित्तीय स्कोर:", "Project Cost:": "परियोजना लागत:", "Monthly EMI:": "मासिक ईएमआई:", "Close Comparison": "तुलना बंद करें",
    "Two-Wheeler Workshop & Spare Parts": "दोपहिया कार्यशाला और स्पेयर पार्ट्स", "Establishment of small-scale dairy unit (2-5 milch cattle) with milk chilling/chilling center supply chain connection.": "दूध शीतकरण केंद्र की आपूर्ति शृंखला से जुड़ी 2–5 दुधारू पशुओं की लघु डेयरी इकाई।", "Broiler or layer poultry farm setup supplying local meat shops, weekly haats, and roadside dhabas.": "स्थानीय मांस दुकानों, साप्ताहिक हाट और ढाबों को आपूर्ति करने वाली ब्रॉयलर या लेयर पोल्ट्री इकाई।", "Custom tailoring, stitching, alteration, and ready-made garment sales center for rural households.": "ग्रामीण परिवारों के लिए सिलाई, कपड़ों में बदलाव और रेडीमेड परिधान बिक्री केंद्र।", "Commercial grain grinding mill for wheat, maize, pulses, and spices serving village households.": "ग्रामीण परिवारों के लिए गेहूं, मक्का, दाल और मसाले पीसने की वाणिज्यिक चक्की।", "Servicing, repair, tire vulcanizing, and spare parts retail for motorcycles and scooters.": "मोटरसाइकिल और स्कूटर की सर्विस, मरम्मत, टायर वल्कनाइजिंग और स्पेयर पार्ट्स बिक्री।"
  },
  mr: {
    "Prototype": "प्रोटोटाइप", "Rural Feasibility & Literacy": "ग्रामीण व्यवहार्यता आणि साक्षरता", "Recommendations use prototype data and do not guarantee business success.": "शिफारसी प्रोटोटाइप डेटावर आधारित आहेत आणि व्यवसायाच्या यशाची हमी देत नाहीत.",
    "Three-way fit analysis": "3-मार्ग योग्यता विश्लेषण", "1. Business ↔ Location": "1. व्यवसाय ↔ ठिकाण", "Market feasibility & local demand": "बाजार व्यवहार्यता आणि स्थानिक मागणी", "2. Person ↔ Business": "2. व्यक्ती ↔ व्यवसाय", "Entrepreneur readiness & resources": "उद्योजक तयारी आणि संसाधने", "3. Person ↔ Finance": "3. व्यक्ती ↔ अर्थव्यवस्था", "Financial fit & debt capacity": "आर्थिक योग्यता आणि कर्ज क्षमता", "Converges into": "परिणाम", "Better Decision": "चांगला निर्णय",
    "Category profile": "श्रेणी प्रोफाइल", "Capital requirement:": "भांडवलाची गरज:", "Demand drivers": "मागणीचे घटक", "Supply signals": "पुरवठा संकेत", "Risk factors": "जोखीम घटक", "Loading business category details...": "व्यवसाय श्रेणीचे तपशील लोड होत आहेत...", "Close Profile": "प्रोफाइल बंद करा",
    "Side-by-side comparison": "शेजारी तुलना", "Compare Past Assessments": "मागील मूल्यमापनांची तुलना", "Assessment A": "मूल्यमापन A", "Assessment B": "मूल्यमापन B", "Market Score:": "बाजार गुण:", "Readiness Score:": "तयारी गुण:", "Financial Score:": "आर्थिक गुण:", "Project Cost:": "प्रकल्प खर्च:", "Monthly EMI:": "मासिक ईएमआय:", "Close Comparison": "तुलना बंद करा",
    "Two-Wheeler Workshop & Spare Parts": "दुचाकी कार्यशाळा आणि सुटे भाग", "Establishment of small-scale dairy unit (2-5 milch cattle) with milk chilling/chilling center supply chain connection.": "दूध शीतकरण केंद्राच्या पुरवठा साखळीशी जोडलेले 2–5 दुभत्या जनावरांचे लघु दुग्ध युनिट।", "Broiler or layer poultry farm setup supplying local meat shops, weekly haats, and roadside dhabas.": "स्थानिक मांस दुकाने, साप्ताहिक बाजार आणि ढाब्यांना पुरवठा करणारे ब्रॉयलर किंवा लेयर कुक्कुट युनिट।", "Custom tailoring, stitching, alteration, and ready-made garment sales center for rural households.": "ग्रामीण कुटुंबांसाठी शिवणकाम, कपड्यांतील बदल आणि तयार कपड्यांचे विक्री केंद्र।", "Commercial grain grinding mill for wheat, maize, pulses, and spices serving village households.": "गावातील कुटुंबांसाठी गहू, मका, डाळी आणि मसाले दळणारी व्यावसायिक गिरणी।", "Servicing, repair, tire vulcanizing, and spare parts retail for motorcycles and scooters.": "मोटरसायकल आणि स्कूटरची सर्व्हिस, दुरुस्ती, टायर व्हल्कनायझिंग आणि सुटे भाग विक्री।"
  }
};

const LANDING_TRANSLATIONS = {
  hi: {
    "Loading Udyam Gram...": "उद्यम ग्राम लोड हो रहा है...",
    "How it works": "यह कैसे काम करता है", "What we assess": "हम क्या जांचते हैं", "Why it matters": "यह क्यों महत्वपूर्ण है", "Start assessment": "मूल्यांकन शुरू करें", "Data-driven guidance before debt": "ऋण से पहले डेटा-आधारित मार्गदर्शन", "Make better business decisions before taking a loan.": "ऋण लेने से पहले बेहतर व्यवसाय निर्णय लें।", "Udyam Gram is a pre-investment advisory platform that tells a rural entrepreneur whether a specific business idea is viable at their village location, whether they are personally ready, and whether they can afford financing — before debt is taken.": "उद्यम ग्राम एक निवेश-पूर्व सलाह मंच है जो ग्रामीण उद्यमी को ऋण लेने से पहले बताता है कि कोई व्यवसाय विचार उसके गांव में व्यवहार्य है या नहीं, वह स्वयं तैयार है या नहीं और वित्तपोषण वहन कर सकता है या नहीं।", "See how it works": "जानें यह कैसे काम करता है", "Clear recommendations": "स्पष्ट सिफारिशें", "Practical action plan": "व्यावहारिक कार्ययोजना", "No guaranteed outcomes": "परिणाम की गारंटी नहीं", "The three-way fit": "3-तरफा उपयुक्तता", "A business can look good on paper and still be wrong for you.": "कागज़ पर अच्छा दिखने वाला व्यवसाय भी आपके लिए गलत हो सकता है।", "We evaluate feasibility through three distinct, un-blended perspectives.": "हम तीन अलग-अलग दृष्टिकोणों से व्यवहार्यता का मूल्यांकन करते हैं।", "Business ↔ Location": "व्यवसाय ↔ स्थान", "Is there sufficient unmet demand, local population, and road infrastructure in the 10km catchment?": "क्या 10 किमी क्षेत्र में पर्याप्त अपूर्ण मांग, जनसंख्या और सड़क ढांचा है?", "Person ↔ Business": "व्यक्ति ↔ व्यवसाय", "Do you personally possess the skills, workspace, supplier links, and committed customers to run it?": "क्या आपके पास इसे चलाने के कौशल, कार्यस्थल, आपूर्तिकर्ता संपर्क और प्रतिबद्ध ग्राहक हैं?", "Person ↔ Finance": "व्यक्ति ↔ वित्त", "Can your monthly disposable income support loan EMI repayments without straining household expenses?": "क्या आपकी मासिक उपलब्ध आय घरेलू खर्च पर दबाव डाले बिना ऋण ईएमआई चुका सकती है?", "Transparent advisory": "पारदर्शी सलाह", "Every recommendation shows its reasoning.": "हर सिफारिश अपना कारण बताती है।", "No black-box scoring. Every score comes with positive drivers and attention areas.": "कोई अस्पष्ट स्कोरिंग नहीं। हर स्कोर के साथ सकारात्मक कारण और ध्यान देने के क्षेत्र मिलते हैं।", "Simple 4-step process": "सरल 4-चरण प्रक्रिया", "Our mission": "हमारा उद्देश्य", "Credit should support a good decision—not create an avoidable burden.": "ऋण अच्छे निर्णय में सहायक होना चाहिए—टाला जा सकने वाला बोझ नहीं बनना चाहिए।", "Taking a loan for an unviable business in a low-demand village creates severe debt distress. Udyam Gram helps rural entrepreneurs verify feasibility before signing loan documents.": "कम मांग वाले गांव में अव्यवहार्य व्यवसाय के लिए ऋण लेना गंभीर कर्ज संकट पैदा कर सकता है। उद्यम ग्राम ऋण दस्तावेज़ पर हस्ताक्षर से पहले व्यवहार्यता जांचने में मदद करता है।", "Hyper-Local Rural Business Feasibility Prototype": "अति-स्थानीय ग्रामीण व्यवसाय व्यवहार्यता प्रोटोटाइप", "All rights reserved.": "सर्वाधिकार सुरक्षित।",
    "Hyper-Local Market Analysis": "अति-स्थानीय बाज़ार विश्लेषण", "Evaluate demand drivers, competitor density, and infrastructure within 10 km radius.": "10 किमी क्षेत्र में मांग के कारक, प्रतिस्पर्धी घनत्व और बुनियादी ढांचा जांचें।", "Assess domain skill, workspace access, supplier networks, and customer commitments.": "क्षेत्रीय कौशल, कार्यस्थल, आपूर्तिकर्ता नेटवर्क और ग्राहक प्रतिबद्धताएं जांचें।", "Financial Fit & EMI Ratio": "वित्तीय उपयुक्तता और ईएमआई अनुपात", "Verify disposable capacity against reducing-balance EMI to prevent loan default.": "ऋण चूक से बचने के लिए घटती शेष राशि वाली ईएमआई के मुकाबले उपलब्ध क्षमता जांचें।", "Rank 5 business categories to uncover stronger alternative opportunities.": "बेहतर वैकल्पिक अवसर खोजने के लिए 5 व्यवसाय श्रेणियों की रैंकिंग करें।", "Risk Awareness": "जोखिम जागरूकता", "Identify local market risk factors before committing margin capital.": "मार्जिन पूंजी लगाने से पहले स्थानीय बाज़ार जोखिम पहचानें।", "Scheme Guidance": "योजना मार्गदर्शन", "Match official government loan schemes (Micro Finance & Term Loan tiers).": "आधिकारिक सरकारी ऋण योजनाओं का मिलान करें (सूक्ष्म वित्त और सावधि ऋण)।", "Plain-language explanations of EMI, moratorium interest, and cash reserves.": "ईएमआई, स्थगन ब्याज और नकद आरक्षित निधि की सरल व्याख्या।", "Explainable Recommendations": "व्याख्यायुक्त सिफारिशें", "Clear positive factors and attention areas for every feasibility score.": "हर व्यवहार्यता स्कोर के सकारात्मक कारक और ध्यान देने के क्षेत्र।", "Tell us about yourself": "अपने बारे में बताएं", "Share your business experience, available resources, and financial background.": "अपना व्यवसाय अनुभव, उपलब्ध संसाधन और वित्तीय पृष्ठभूमि बताएं।", "Select business & location": "व्यवसाय और स्थान चुनें", "Choose from 5 business categories and pick your village location.": "5 व्यवसाय श्रेणियों में से चुनें और गांव का स्थान तय करें।", "Analyse local fit": "स्थानीय उपयुक्तता जांचें", "Our deterministic engines process local market signals, readiness, and EMI capacity.": "हमारे निर्धारित इंजन स्थानीय बाज़ार संकेत, तत्परता और ईएमआई क्षमता जांचते हैं।", "Receive practical action plan": "व्यावहारिक कार्ययोजना पाएं", "Get an actionable preparation checklist and legal office guidance.": "तैयारी की कार्यसूची और कानूनी कार्यालय मार्गदर्शन पाएं।"
  },
  mr: {
    "Loading Udyam Gram...": "उद्यम ग्राम लोड होत आहे...",
    "How it works": "हे कसे कार्य करते", "What we assess": "आम्ही काय तपासतो", "Why it matters": "हे का महत्त्वाचे आहे", "Start assessment": "मूल्यमापन सुरू करा", "Data-driven guidance before debt": "कर्जापूर्वी डेटा-आधारित मार्गदर्शन", "Make better business decisions before taking a loan.": "कर्ज घेण्यापूर्वी चांगले व्यवसाय निर्णय घ्या।", "Udyam Gram is a pre-investment advisory platform that tells a rural entrepreneur whether a specific business idea is viable at their village location, whether they are personally ready, and whether they can afford financing — before debt is taken.": "उद्यम ग्राम हे गुंतवणूक-पूर्व सल्ला व्यासपीठ आहे. कर्ज घेण्यापूर्वी व्यवसाय कल्पना गावात व्यवहार्य आहे का, उद्योजक स्वतः तयार आहे का आणि वित्तपुरवठा परवडतो का हे ते सांगते।", "See how it works": "हे कसे कार्य करते ते पहा", "Clear recommendations": "स्पष्ट शिफारसी", "Practical action plan": "व्यावहारिक कृती योजना", "No guaranteed outcomes": "परिणामाची हमी नाही", "The three-way fit": "3-मार्ग योग्यता", "A business can look good on paper and still be wrong for you.": "कागदावर चांगला दिसणारा व्यवसायही तुमच्यासाठी चुकीचा असू शकतो।", "We evaluate feasibility through three distinct, un-blended perspectives.": "आम्ही तीन स्वतंत्र दृष्टिकोनांतून व्यवहार्यतेचे मूल्यमापन करतो।", "Business ↔ Location": "व्यवसाय ↔ ठिकाण", "Is there sufficient unmet demand, local population, and road infrastructure in the 10km catchment?": "10 किमी परिसरात पुरेशी अपूर्ण मागणी, लोकसंख्या आणि रस्ते सुविधा आहेत का?", "Person ↔ Business": "व्यक्ती ↔ व्यवसाय", "Do you personally possess the skills, workspace, supplier links, and committed customers to run it?": "तो चालवण्यासाठी तुमच्याकडे कौशल्ये, कार्यस्थळ, पुरवठादार संपर्क आणि वचनबद्ध ग्राहक आहेत का?", "Person ↔ Finance": "व्यक्ती ↔ अर्थव्यवस्था", "Can your monthly disposable income support loan EMI repayments without straining household expenses?": "तुमचे मासिक उपलब्ध उत्पन्न घरखर्चावर ताण न आणता कर्ज ईएमआय भरू शकते का?", "Transparent advisory": "पारदर्शक मार्गदर्शन", "Every recommendation shows its reasoning.": "प्रत्येक शिफारस तिचे कारण दाखवते।", "No black-box scoring. Every score comes with positive drivers and attention areas.": "अस्पष्ट गुणांकन नाही. प्रत्येक गुणासोबत सकारात्मक कारणे आणि लक्ष देण्याचे भाग आहेत।", "Simple 4-step process": "सोपी 4-टप्प्यांची प्रक्रिया", "Our mission": "आमचे ध्येय", "Credit should support a good decision—not create an avoidable burden.": "कर्जाने चांगल्या निर्णयाला साथ द्यावी—टाळता येणारे ओझे निर्माण करू नये।", "Taking a loan for an unviable business in a low-demand village creates severe debt distress. Udyam Gram helps rural entrepreneurs verify feasibility before signing loan documents.": "कमी मागणीच्या गावात अव्यवहार्य व्यवसायासाठी कर्ज घेतल्यास गंभीर कर्जताण निर्माण होतो. उद्यम ग्राम कर्ज कागदपत्रांवर स्वाक्षरीपूर्वी व्यवहार्यता तपासण्यास मदत करते।", "Hyper-Local Rural Business Feasibility Prototype": "अतिस्थानिक ग्रामीण व्यवसाय व्यवहार्यता प्रोटोटाइप", "All rights reserved.": "सर्व हक्क राखीव।",
    "Hyper-Local Market Analysis": "अतिस्थानिक बाजार विश्लेषण", "Evaluate demand drivers, competitor density, and infrastructure within 10 km radius.": "10 किमी परिसरातील मागणीचे घटक, स्पर्धक घनता आणि पायाभूत सुविधा तपासा।", "Assess domain skill, workspace access, supplier networks, and customer commitments.": "क्षेत्रीय कौशल्य, कार्यस्थळ, पुरवठादार जाळे आणि ग्राहक वचनबद्धता तपासा।", "Financial Fit & EMI Ratio": "आर्थिक योग्यता आणि ईएमआय प्रमाण", "Verify disposable capacity against reducing-balance EMI to prevent loan default.": "कर्ज थकबाकी टाळण्यासाठी घटत्या शिल्लक रकमेच्या ईएमआयच्या तुलनेत उपलब्ध क्षमता तपासा।", "Rank 5 business categories to uncover stronger alternative opportunities.": "चांगले पर्यायी अवसर शोधण्यासाठी 5 व्यवसाय श्रेणींची क्रमवारी लावा।", "Risk Awareness": "जोखीम जागरूकता", "Identify local market risk factors before committing margin capital.": "मार्जिन भांडवल गुंतवण्यापूर्वी स्थानिक बाजार जोखीम ओळखा।", "Scheme Guidance": "योजना मार्गदर्शन", "Match official government loan schemes (Micro Finance & Term Loan tiers).": "अधिकृत सरकारी कर्ज योजनांची जुळवणी करा (सूक्ष्म वित्त आणि मुदत कर्ज)।", "Plain-language explanations of EMI, moratorium interest, and cash reserves.": "ईएमआय, स्थगिती व्याज आणि रोख राखीव निधीचे सोपे स्पष्टीकरण।", "Explainable Recommendations": "स्पष्टीकरणासह शिफारसी", "Clear positive factors and attention areas for every feasibility score.": "प्रत्येक व्यवहार्यता गुणासाठी सकारात्मक घटक आणि लक्ष देण्याचे भाग।", "Tell us about yourself": "स्वतःबद्दल सांगा", "Share your business experience, available resources, and financial background.": "व्यवसाय अनुभव, उपलब्ध संसाधने आणि आर्थिक पार्श्वभूमी सांगा।", "Select business & location": "व्यवसाय आणि ठिकाण निवडा", "Choose from 5 business categories and pick your village location.": "5 व्यवसाय श्रेणींमधून निवडा आणि गावाचे ठिकाण ठरवा।", "Analyse local fit": "स्थानिक योग्यता तपासा", "Our deterministic engines process local market signals, readiness, and EMI capacity.": "आमची निश्चित इंजिने स्थानिक बाजार संकेत, तयारी आणि ईएमआय क्षमता तपासतात।", "Receive practical action plan": "व्यावहारिक कृती योजना मिळवा", "Get an actionable preparation checklist and legal office guidance.": "तयारीची कृतीसूची आणि कायदेशीर कार्यालय मार्गदर्शन मिळवा।"
  }
};

export const LanguageProvider = ({ children }) => {
  const storedLanguage = localStorage.getItem('preferred_language');
  const [lang, setLangState] = useState(
    LANGUAGES_LIST.some(({ code }) => code === storedLanguage) ? storedLanguage : 'en'
  );

  const setLang = (code) => {
    localStorage.setItem('preferred_language', code);
    setLangState(code);
  };

  const t = (text) => {
    if (text === null || text === undefined || typeof text !== 'string') return text;
    const cleanText = text.replace(/^\[(?:Hindi|Marathi)\]\s*/i, '');
    if (lang === 'en') return cleanText;
    const langDict = {
      ...UI_TRANSLATIONS[lang],
      ...PROTOTYPE_TRANSLATIONS[lang],
      ...ADDITIONAL_TRANSLATIONS[lang],
      ...API_FRAGMENT_TRANSLATIONS[lang],
      ...SHARED_TRANSLATIONS[lang],
      ...LANDING_TRANSLATIONS[lang]
    };
    if (langDict[cleanText]) return langDict[cleanText];

    // Translate known fragments inside deterministic API sentences (category
    // names and their surrounding prototype explanation templates).
    let translated = cleanText;
    Object.entries(langDict)
      .sort(([a], [b]) => b.length - a.length)
      .forEach(([source, target]) => {
        if (source.length >= 4 && translated.includes(source)) {
          translated = translated.split(source).join(target);
        }
      });
    return translated;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, languagesList: LANGUAGES_LIST, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
