import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES_LIST = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' }
];

const UI_TRANSLATIONS = {
  hi: {
    "Dashboard": "डैशबोर्ड",
    "New Assessment": "नया मूल्यांकन",
    "New assessment": "नया मूल्यांकन",
    "Reports History": "रिपोर्ट इतिहास",
    "Reports": "रिपोर्ट्स",
    "Improvement Plan": "सुधार योजना",
    "Business Alternatives": "व्यवसाय विकल्प",
    "Financial Plan": "वित्तीय योजना",
    "Legal Advice": "कानूनी सलाह",
    "Legal Advice & Documentation": "कानूनी सलाह एवं दस्तावेज़ीकरण",
    "Profile": "प्रोफ़ाइल",
    "Sign Out": "साइन आउट",
    "Decision tools": "निर्णय उपकरण",
    "Prototype data": "प्रारूप डेटा",
    "Decision Dashboard": "निर्णय डैशबोर्ड",
    "Your business assessment": "आपका व्यवसाय मूल्यांकन",
    "Pre-investment advisory overview and village catchment intelligence.": "निवेश-पूर्व सलाह अवलोकन और ग्रामीण मांग बुद्धिमत्ता।",
    "Full report": "पूर्ण रिपोर्ट",
    "Latest assessment": "नवीनतम मूल्यांकन",
    "Local catchment · 10 km": "स्थानीय क्षेत्र · 10 किमी",
    "Map view": "मानचित्र दृश्य",
    "No completed assessments yet": "अभी तक कोई पूर्ण मूल्यांकन नहीं",
    "Start your first assessment": "अपना पहला मूल्यांकन शुरू करें",
    "Back to results": "परिणामों पर वापस",
    "Download report": "रिपोर्ट डाउनलोड करें",
    "Print plan": "योजना प्रिंट करें",
    "Compare Selected (2)": "चयनित की तुलना करें (2)",
    "Compare Selected": "चयनित की तुलना करें",
    "Begin assessment": "मूल्यांकन शुरू करें",
    "Continue to business": "व्यवसाय पर जारी रखें",
    "Continue to readiness": "तैयारी पर जारी रखें",
    "Continue to finance": "वित्त पर जारी रखें",
    "Continue to review": "समीक्षा पर जारी रखें",
    "Run Feasibility Analysis →": "व्यवहार्यता विश्लेषण चलाएं →",
    "Back": "वापस",
    "Edit": "संपादित करें",
    "Save changes": "बदलाव सहेजें",
    "Log in": "लॉग इन",
    "Create account": "खाता बनाएं",
    "Notifications": "सूचनाएं",
    "No new notifications": "कोई नई सूचना नहीं",
    "Local Market Fit": "स्थानीय बाज़ार फिट",
    "Entrepreneur Readiness": "उद्यमी तत्परता",
    "Financial Fit": "वित्तीय फिट",
    "Verdict Band": "फैसला बैंड",
    "Feasibility": "व्यवहार्यता",
    "Strengths": "ताकत",
    "Weaknesses": "कमजोरियां",
    "Opportunities": "अवसर",
    "Threats": "खतरे",
    "Market Fit": "बाज़ार फिट",
    "Capital Fit": "पूंजी फिट",
    "Resource Fit": "संसाधन फिट",
    "Best fit": "सर्वोत्तम फिट",
    "Fit score": "फिट स्कोर",
    "Recommended Schemes": "अनुशंसित योजनाएं",
    "Estimated EMI": "अनुमानित ईएमआई",
    "Monthly Profit": "मासिक लाभ",
    "Break-even Period": "ब्रेक-इवन अवधि",
    "Priority Actions": "प्राथमिकता वाले कार्य",
    "Legal Advice & Registration Support": "कानूनी सलाह और पंजीकरण सहायता",
    "Assessment history": "मूल्यांकन इतिहास",
    "User Profile": "उपयोगकर्ता प्रोफ़ाइल",
    "Personal details": "व्यक्तिगत विवरण",
    "Accessibility Settings": "सुलभता सेटिंग्स"
  },
  mr: {
    "Dashboard": "डॅशबोर्ड",
    "New Assessment": "नवीन मूल्यमापन",
    "New assessment": "नवीन मूल्यमापन",
    "Reports History": "अहवाल इतिहास",
    "Reports": "अहवाल",
    "Improvement Plan": "सुधारणा योजना",
    "Business Alternatives": "व्यवसाय पर्याय",
    "Financial Plan": "आर्थिक योजना",
    "Legal Advice": "कायदेशीर सल्ला",
    "Legal Advice & Documentation": "कायदेशीर सल्ला आणि कागदपत्रे",
    "Profile": "प्रोफाइल",
    "Sign Out": "साइन आउट",
    "Decision tools": "निर्णय साधने",
    "Prototype data": "प्रोटोटाइप डेटा",
    "Decision Dashboard": "निर्णय डॅशबोर्ड",
    "Your business assessment": "तुमचे व्यवसाय मूल्यमापन",
    "Pre-investment advisory overview and village catchment intelligence.": "गुंतवणूक-पूर्व सल्लागार विहंगावलोकन आणि ग्रामीण मागणी बुद्धिमत्ता.",
    "Full report": "पूर्ण अहवाल",
    "Latest assessment": "नवीनतम मूल्यमापन",
    "Local catchment · 10 km": "स्थानिक परिसर · १० किमी",
    "Map view": "नकाशा दृश्य",
    "No completed assessments yet": "अद्याप कोणतेही पूर्ण मूल्यमापन नाही",
    "Start your first assessment": "तुमचे पहिले मूल्यमापन सुरू करा",
    "Back to results": "निकाल कडे परत",
    "Download report": "अहवाल डाउनलोड करा",
    "Print plan": "योजना प्रिंट करा",
    "Compare Selected (2)": "निवडलेल्यांची तुलना करा (2)",
    "Compare Selected": "निवडलेल्यांची तुलना करा",
    "Begin assessment": "मूल्यमापन सुरू करा",
    "Continue to business": "व्यवसायाकडे पुढे जा",
    "Continue to readiness": "तयारीकडे पुढे जा",
    "Continue to finance": "आर्थिक बाबींकडे पुढे जा",
    "Continue to review": "पुनरावलोकनाकडे पुढे जा",
    "Run Feasibility Analysis →": "व्यावहारिकता विश्लेषण चालवा →",
    "Back": "मागे",
    "Edit": "संपादित करा",
    "Save changes": "बदल जतन करा",
    "Log in": "लॉग इन",
    "Create account": "खाते तयार करा",
    "Notifications": "सूचना",
    "No new notifications": "नवीन सूचना नाहीत",
    "Local Market Fit": "स्थानिक बाजार फिट",
    "Entrepreneur Readiness": "उद्योजक तयारी",
    "Financial Fit": "आर्थिक फिट",
    "Verdict Band": "निर्णय बँड",
    "Feasibility": "व्यावहारिकता",
    "Strengths": "सामर्थ्ये",
    "Weaknesses": "उणिवा",
    "Opportunities": "संधी",
    "Threats": "धोके",
    "Market Fit": "बाजार फिट",
    "Capital Fit": "भांडवल फिट",
    "Resource Fit": "संसाधन फिट",
    "Best fit": "सर्वोत्तम फिट",
    "Fit score": "फिट स्कोर",
    "Recommended Schemes": "शिफारस केलेल्या योजना",
    "Estimated EMI": "अंदाजित ईएमआय",
    "Monthly Profit": "मासिक नफा",
    "Break-even Period": "ब्रेक-इव्हन कालावधी",
    "Priority Actions": "प्राधान्य कृती",
    "Legal Advice & Registration Support": "कायदेशीर सल्ला आणि नोंदणी मदत",
    "Assessment history": "मूल्यमापन इतिहास",
    "User Profile": "वापरकर्ता प्रोफाइल",
    "Personal details": "वैयक्तिक तपशील",
    "Accessibility Settings": "सुलभता सेटिंग्ज"
  },
  ta: {
    "Dashboard": "டாஷ்போர்டு",
    "New Assessment": "புதிய மதிப்பீடு",
    "New assessment": "புதிய மதிப்பீடு",
    "Reports History": "அறிக்கைகள் வரலாறு",
    "Reports": "அறிக்கைகள்",
    "Improvement Plan": "மேம்பாட்டுத் திட்டம்",
    "Business Alternatives": "வணிக மாற்றுக்கள்",
    "Financial Plan": "நிதித் திட்டம்",
    "Legal Advice": "சட்ட ஆலோசனை",
    "Legal Advice & Documentation": "சட்ட ஆலோசனை & ஆவணங்கள்",
    "Profile": "சுயவிவரம்",
    "Sign Out": "வெளியேறு",
    "Decision tools": "முடிவு கருவிகள்",
    "Prototype data": "முன்னோடி தரவு",
    "Decision Dashboard": "முடிவு டாஷ்போர்டு",
    "Your business assessment": "உங்கள் வணிக மதிப்பீடு",
    "Full report": "முழு அறிக்கை",
    "Latest assessment": "சமீபத்திய மதிப்பீடு",
    "Back to results": "முடிவுகளுக்குத் திரும்பு",
    "Download report": "அறிக்கையைப் பதிவிறக்குக",
    "Print plan": "திட்டத்தை அச்சிடுக",
    "Compare Selected": "தேர்ந்தெடுக்கப்பட்டதை ஒப்பிடுக",
    "Begin assessment": "மதிப்பீட்டைத் தொடங்குங்கள்",
    "Continue to business": "வணிகத்திற்கு தொடரவும்",
    "Continue to readiness": "தயார்நிலைக்கு தொடரவும்",
    "Continue to finance": "நிதிக்கு தொடரவும்",
    "Continue to review": "மதிப்பாய்வுக்கு தொடரவும்",
    "Run Feasibility Analysis →": "சாத்தியக்கூறு பகுப்பாய்வு செய்க →",
    "Back": "பின்னால்",
    "Edit": "திருத்து",
    "Save changes": "மாற்றங்களைச் சேமிக்கவும்",
    "Log in": "உள்நுழைய",
    "Create account": "கணக்கை உருவாக்கு",
    "Notifications": "அறிவிப்புகள்",
    "No new notifications": "புதிய அறிவிப்புகள் இல்லை",
    "Local Market Fit": "உள்ளூர் சந்தை பொருத்தம்",
    "Entrepreneur Readiness": "தொழில்முனைவோர் தயார்நிலை",
    "Financial Fit": "நிதி பொருத்தம்",
    "Strengths": "பலம்",
    "Weaknesses": "பலவீனம்",
    "Opportunities": "வாய்ப்புகள்",
    "Threats": "அச்சுறுத்தல்கள்",
    "Priority Actions": "முன்னுரிமை நடவடிக்கைகள்"
  },
  te: {
    "Dashboard": "డాష్‌బోర్డ్",
    "New Assessment": "కొత్త మూల్యాంకనం",
    "New assessment": "కొత్త మూల్యాంకనం",
    "Reports History": "నివేదికల చరిత్ర",
    "Reports": "నివేదికలు",
    "Improvement Plan": "మెరుగుదల ప్రణాళిక",
    "Business Alternatives": "వ్యాపార ప్రత్యామ్నాయాలు",
    "Financial Plan": "ఆర్థిక ప్రణాళిక",
    "Legal Advice": "చట్టపరమైన సలహా",
    "Legal Advice & Documentation": "చట్టపరమైన సలహా & పత్రాలు",
    "Profile": "ప్రొఫైల్",
    "Sign Out": "సైన్ అవుట్",
    "Decision tools": "నిర్ణయ సాధనాలు",
    "Prototype data": "ప్రోటోటైప్ డేటా",
    "Decision Dashboard": "నిర్ణయ డాష్‌బోర్డ్",
    "Your business assessment": "మీ వ్యాపార మూల్యాంకనం",
    "Full report": "పూర్తి నివేదిక",
    "Latest assessment": "ఇటీవలి మూల్యాంకనం",
    "Back to results": "ఫలితాలకు తిరిగి వెళ్లండి",
    "Download report": "నివేదికను డౌన్‌లోడ్ చేయండి",
    "Print plan": "ప్రణాళికను ప్రింట్ చేయండి",
    "Compare Selected": "ఎంచుకున్న వాటిని పోల్చండి",
    "Begin assessment": "మూల్యాంకనం ప్రారంభించండి",
    "Back": "వెనుకకు",
    "Edit": "సవరించు",
    "Save changes": "మార్పులను సేవ్ చేయండి",
    "Log in": "లాగిన్",
    "Create account": "ఖాతా సృష్టించండి",
    "Notifications": "నోటిఫికేషన్‌లు",
    "No new notifications": "కొత్త నోటిఫికేషన్‌లు లేవు",
    "Priority Actions": "ప్రాధాన్యతా చర్యలు"
  },
  kn: {
    "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "New Assessment": "ಹೊಸ ಮೌಲ್ಯಮಾಪನ",
    "New assessment": "ಹೊಸ ಮೌಲ್ಯಮಾಪನ",
    "Reports History": "ವರದಿಗಳ ಇತಿಹಾಸ",
    "Reports": "ವರದಿಗಳು",
    "Improvement Plan": "ಸುಧಾರಣಾ ಯೋಜನೆ",
    "Business Alternatives": "ವ್ಯಾಪಾರ ಪರ್ಯಾಯಗಳು",
    "Financial Plan": "ಹಣಕಾಸು ಯೋಜನೆ",
    "Legal Advice": "ಕಾನ್ಫರೆನ್ಸ್ ಸಲಹೆ",
    "Legal Advice & Documentation": "ಕಾನ್ಫರೆನ್ಸ್ ಸಲಹೆ ಮತ್ತು ದಾಖಲೆಗಳು",
    "Profile": "ಪ್ರೊಫೈಲ್",
    "Sign Out": "ಸೈನ್ ಔಟ್",
    "Decision tools": "ನಿರ್ಧಾರ ಉಪಕರಣಗಳು",
    "Full report": "ಸಂಪೂರ್ಣ ವರದಿ",
    "Latest assessment": "ಇತ್ತೀಚಿನ ಮೌಲ್ಯಮಾಪನ",
    "Back to results": "ಫಲಿತಾಂಶಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    "Download report": "ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    "Print plan": "ಯೋಜನೆಯನ್ನು ಮುದ್ರಿಸಿ",
    "Compare Selected": "ಆಯ್ಕೆಮಾಡಿದ್ದನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ",
    "Begin assessment": "ಮೌಲ್ಯಮಾಪನ ಪ್ರಾರಂಭಿಸಿ",
    "Back": "ಹಿಂತಿರುಗಿ",
    "Edit": "ಸಂಪಾದಿಸಿ",
    "Save changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    "Log in": "ಲಾಗಿನ್",
    "Create account": "ಖಾತೆ ರಚಿಸಿ",
    "Notifications": "ಸೂಚನೆಗಳು",
    "No new notifications": "ಯಾವುದೇ ಹೊಸ ಸೂಚನೆಗಳಿಲ್ಲ",
    "Priority Actions": "ಆದ್ಯತೆಯ ಕ್ರಮಗಳು"
  },
  bn: {
    "Dashboard": "ড্যাশবোর্ড",
    "New Assessment": "নতুন মূল্যায়ন",
    "New assessment": "নতুন মূল্যায়ন",
    "Reports History": "রিপোর্টের ইতিহাস",
    "Reports": "রিপোর্ট",
    "Improvement Plan": "উন্নয়ন পরিকল্পনা",
    "Business Alternatives": "ব্যবসার বিকল্প",
    "Financial Plan": "আর্থিক পরিকল্পনা",
    "Legal Advice": "আইনি পরামর্শ",
    "Legal Advice & Documentation": "আইনি পরামর্শ ও নথিপত্র",
    "Profile": "প্রোফাইল",
    "Sign Out": "সাইন আউট",
    "Decision tools": "সিদ্ধান্তের সরঞ্জাম",
    "Full report": "সম্পূর্ণ রিপোর্ট",
    "Latest assessment": "সাম্প্রতিক মূল্যায়ন",
    "Back to results": "ফলাফলে ফিরে যান",
    "Download report": "রিপোর্ট ডাউনলোড করুন",
    "Print plan": "পরিকল্পনা প্রিন্ট করুন",
    "Compare Selected": "নির্বাচিতগুলি তুলনা করুন",
    "Begin assessment": "মূল্যায়ন শুরু করুন",
    "Back": "ফিরে যান",
    "Edit": "সম্পাদনা করুন",
    "Save changes": "পরিবর্তনগুলি সংরক্ষণ করুন",
    "Log in": "লগ ইন",
    "Create account": "অ্যাকাউন্ট তৈরি করুন",
    "Notifications": "বিজ্ঞপ্তি",
    "No new notifications": "কোনো নতুন বিজ্ঞপ্তি নেই",
    "Priority Actions": "অগ্রাধিকার পদক্ষেপ"
  },
  gu: {
    "Dashboard": "ડેશબોર્ડ",
    "New Assessment": "નવું મૂલ્યાંકન",
    "New assessment": "નવું મૂલ્યાંકન",
    "Reports History": "રિપોર્ટ ઇતિહાસ",
    "Reports": "રિપોર્ટ્સ",
    "Improvement Plan": "સુધારણા યોજના",
    "Business Alternatives": "વ્યવસાય વિકલ્પો",
    "Financial Plan": "નાણાકીય યોજના",
    "Legal Advice": "કાનૂની સલાહ",
    "Legal Advice & Documentation": "કાનૂની સલાહ અને દસ્તાવેજીકરણ",
    "Profile": "પ્રોફાઇલ",
    "Sign Out": "સાઇન આઉટ",
    "Decision tools": "નિર્ણય સાધનો",
    "Full report": "સંપૂર્ણ રિપોર્ટ",
    "Latest assessment": "તાજેતરનું મૂલ્યાંકન",
    "Back to results": "પરિણામો પર પાછા ફરો",
    "Download report": "રિપોર્ટ ડાઉનલોડ કરો",
    "Print plan": "યોજના પ્રિન્ટ કરો",
    "Compare Selected": "પસંદ કરેલાની સરખામણી કરો",
    "Begin assessment": "મૂલ્યાંકન શરૂ કરો",
    "Back": "પાછા",
    "Edit": "સંપાદિત કરો",
    "Save changes": "ફેરફારો સાચવો",
    "Log in": "લૉગ ઇન",
    "Create account": "ખાતું બનાવો",
    "Notifications": "સૂચનાઓ",
    "No new notifications": "કોઈ નવી સૂચના નથી",
    "Priority Actions": "પ્રાથમિકતા ક્રિયાઓ"
  },
  pa: {
    "Dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "New Assessment": "ਨਵਾਂ ਮੁਲਾਂਕਣ",
    "New assessment": "ਨਵਾਂ ਮੁਲਾਂਕਣ",
    "Reports History": "ਰਿਪੋਰਟ ਇਤਿਹਾਸ",
    "Reports": "ਰਿਪੋਰਟਾਂ",
    "Improvement Plan": "ਸੁਧਾਰ ਯੋਜਨਾ",
    "Business Alternatives": "ਕਾਰੋਬਾਰੀ ਵਿਕਲਪ",
    "Financial Plan": "ਮਾਲੀ ਯੋਜਨਾ",
    "Legal Advice": "ਕਾਨੂੰਨੀ ਸਲਾਹ",
    "Legal Advice & Documentation": "ਕਾਨੂੰਨੀ ਸਲਾਹ ਅਤੇ ਦਸਤਾਵੇਜ਼",
    "Profile": "ਪ੍ਰੋਫਾਈਲ",
    "Sign Out": "ਸਾਈਨ ਆਊਟ",
    "Decision tools": "ਫੈਸਲੇ ਦੇ ਸੰਦ",
    "Full report": "ਪੂਰੀ ਰਿਪੋਰਟ",
    "Latest assessment": "ਤਾਜ਼ਾ ਮੁਲਾਂਕਣ",
    "Back to results": "ਨਤੀਜਿਆਂ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    "Download report": "ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    "Print plan": "ਯੋਜਨਾ ਪ੍ਰਿੰਟ ਕਰੋ",
    "Compare Selected": "ਚੁਣੇ ਗਏ ਦੀ ਤੁਲਨਾ ਕਰੋ",
    "Begin assessment": "ਮੁਲਾਂਕਣ ਸ਼ੁਰੂ ਕਰੋ",
    "Back": "ਵਾਪਸ",
    "Edit": "ਸੋਧੋ",
    "Save changes": "ਬਦਲਾਅ ਸੰਭਾਲੋ",
    "Log in": "ਲੌਗ ਇਨ",
    "Create account": "ਖਾਤਾ ਬਣਾਓ",
    "Notifications": "ਨੋਟੀਫਿਕੇਸ਼ਨ",
    "No new notifications": "ਕੋਈ ਨਵਾਂ ਨੋਟੀਫਿਕੇਸ਼ਨ ਨਹੀਂ",
    "Priority Actions": "ਪਹਿਲ ਦੇ ਕਦਮ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(localStorage.getItem('preferred_language') || 'en');

  const setLang = (code) => {
    localStorage.setItem('preferred_language', code);
    setLangState(code);
  };

  const t = (text) => {
    if (!text || lang === 'en') return text;
    const langDict = UI_TRANSLATIONS[lang];
    if (langDict && langDict[text]) return langDict[text];
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, languagesList: LANGUAGES_LIST, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
